[workspace]
resolver = "2"
members = [
    "omdurman-types",
    "omdurman-hex",
    "omdurman-map",
    "omdurman-net",
    "omdurman-rules",
    "omdurman-app",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
bevy = "0.18"
bevy_egui = "0.39"
bevy_matchbox = "0.14"
avian3d = "0.6"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "3", features = ["indexmap_2"] }
ron = "0.8"
postcard = { version = "1", features = ["alloc"] }
rand = "0.10"
rand_chacha = "0.10"
strum = { version = "0.26", features = ["derive"] }
thiserror = "2"
image = "0.25"
indexmap = { version = "2", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
bevy-color-palettes = "0.3.3-alpha.1"


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
