[package]
name = "asset-editor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "asset-editor"
path = "src/main.rs"

[dependencies]
eframe = "0.31"
egui = "0.31"
env_logger = "0.11"
image = { version = "0.25", default-features = false, features = ["webp"] }
indexmap = { version = "2", features = ["serde"] }
log = "0.4"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
omdurman-rules = { path = "../../omdurman-rules" }
omdurman-types = { path = "../../omdurman-types" }
