# fly.toml app configuration file generated for omdurman-matchbox on 2026-05-09T22:24:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omdurman-matchbox'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3536
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
