//! Auto-generated unit ID enum. Do not edit by hand.
#![allow(non_camel_case_types)]

use omdurman_types::SectionName;
use serde::{Deserialize, Serialize};

/// Stable identifier for a counter on the map.
///
/// Each variant corresponds to a unique `(section, col, row)` position
/// on the sprite sheet, excluding the non-unit `BritishBoats` cells
/// (0,0)-(2,1).
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum UnitId {
    AliWadHelu_0_0,
    AliWadHelu_0_1,
    AliWadHelu_1_0,
    AliWadHelu_1_1,
    AliWadHelu_2_0,
    AliWadHelu_2_1,
    AliWadHelu_3_0,
    AliWadHelu_3_1,
    AliWadHelu_4_0,
    AliWadHelu_4_1,
    AliWadHelu_5_0,
    AliWadHelu_5_1,
    Baggara_0_0,
    Baggara_0_1,
    Baggara_1_0,
    Baggara_1_1,
    Baggara_2_0,
    Baggara_2_1,
    Baggara_3_0,
    Baggara_3_1,
    Baggara_4_0,
    Baggara_4_1,
    Baggara_5_0,
    Baggara_5_1,
    BritishBoats_3_0,
    BritishBoats_3_1,
    BritishBoats_4_0,
    BritishBoats_4_1,
    BritishBoats_5_0,
    BritishBoats_5_1,
    BritishBoats_6_0,
    BritishBoats_6_1,
    BritishBoats_7_0,
    BritishBoats_7_1,
    BritishArmy_0_0,
    BritishArmy_0_1,
    BritishArmy_1_0,
    BritishArmy_1_1,
    BritishArmy_2_0,
    BritishArmy_2_1,
    BritishArmy_3_0,
    BritishArmy_3_1,
    BritishArmy_4_0,
    BritishArmy_4_1,
    BritishArmy_5_0,
    BritishArmy_5_1,
    BritishArmy_6_0,
    BritishArmy_6_1,
    BritishArmy_7_0,
    BritishArmy_7_1,
    Danagla_0_0,
    Degheim_0_0,
    Degheim_0_1,
    Degheim_0_2,
    Degheim_0_3,
    Degheim_0_4,
    EgyptianArmy_0_0,
    EgyptianArmy_0_1,
    EgyptianArmy_1_0,
    EgyptianArmy_1_1,
    EgyptianArmy_2_0,
    EgyptianArmy_2_1,
    EgyptianArmy_3_0,
    EgyptianArmy_3_1,
    EgyptianArmy_4_0,
    EgyptianArmy_4_1,
    EgyptianArmy_5_0,
    EgyptianArmy_5_1,
    EgyptianArmy_6_0,
    EgyptianArmy_6_1,
    EgyptianArmy_7_0,
    EgyptianArmy_7_1,
    Hadendowa_0_0,
    Hadendowa_0_1,
    Hadendowa_1_0,
    Hadendowa_1_1,
    Hadendowa_2_0,
    Hadendowa_2_1,
    Hadendowa_3_0,
    Hadendowa_3_1,
    Hadendowa_4_0,
    Hadendowa_4_1,
    Hadendowa_5_0,
    Hadendowa_5_1,
    Hadendowa_6_0,
    Hadendowa_6_1,
    Hadendowa_7_0,
    Hadendowa_7_1,
    HadendowaForts_0_0,
    HadendowaForts_0_1,
    HadendowaForts_1_0,
    HadendowaForts_1_1,
    HadendowaForts_2_0,
    HadendowaForts_2_1,
    HadendowaForts_3_0,
    HadendowaForts_3_1,
    HadendowaForts_4_0,
    HadendowaForts_4_1,
    HadendowaForts_5_0,
    HadendowaForts_5_1,
    HadendowaForts_6_0,
    HadendowaForts_6_1,
    HadendowaForts_7_0,
    HadendowaForts_7_1,
    Jehadia_0_0,
    Jehadia_0_1,
    Jehadia_1_0,
    Jehadia_1_1,
    Jehadia_2_0,
    Jehadia_2_1,
    Jehadia_3_0,
    Jehadia_3_1,
    Jehadia_4_0,
    Jehadia_4_1,
    Jehadia_5_0,
    Kehena_0_0,
    Kehena_0_1,
    Kehena_0_2,
    Kehena_0_3,
    Kehena_0_4,
    Kehena_0_5,
    KhalifaAbdullah_0_0,
    KhalifaAbdullah_0_1,
    KhalifaAbdullah_1_0,
    KhalifaAbdullah_1_1,
    KhalifaAbdullah_2_0,
    KhalifaAbdullah_2_1,
    Kitchener_0_0,
    Kitchener_0_1,
    Kitchener_1_0,
    Kitchener_1_1,
    Kitchener_2_0,
    Kitchener_2_1,
    Kitchener_3_0,
    Kitchener_3_1,
    Kitchener_4_0,
    Kitchener_4_1,
    Kitchener_5_0,
    Kitchener_5_1,
    Kitchener_6_0,
    Kitchener_6_1,
    Kitchener_7_0,
    Kitchener_7_1,
    JaalinII_0_0,
    JaalinII_0_1,
    JaalinII_1_0,
    JaalinII_1_1,
    JaalinII_2_0,
    JaalinII_2_1,
    JaalinII_3_0,
    JaalinII_3_1,
    JaalinII_4_0,
    JaalinII_4_1,
    JaalinII_5_0,
    JaalinII_5_1,
    MulazminII_0_0,
    MulazminII_0_1,
    MulazminII_1_0,
    MulazminII_1_1,
    MulazminII_2_0,
    MulazminII_2_1,
    MulazminII_3_0,
    MulazminII_3_1,
    MulazminII_4_0,
    MulazminII_4_1,
    MulazminII_5_0,
    MulazminII_5_1,
    MulazminII_6_0,
    MulazminII_6_1,
    MulazminII_7_0,
    MulazminII_7_1,
    Mulazmin_0_0,
    OsmanDigna_0_0,
    SheikElDin_0_0,
    SheikElDin_0_1,
    SheikElDin_1_0,
    SheikElDin_1_1,
    SheikElDin_2_0,
    SheikElDin_2_1,
    SheikElDin_3_0,
    SheikElDin_3_1,
    SheikElDin_4_0,
    SheikElDin_4_1,
    SheikElDin_5_0,
    SheikElDin_5_1,
    SheikElDin_6_0,
    SheikElDin_6_1,
    Sherif_0_0,
    Sherif_1_0,
    Sherif_1_1,
    Sherif_2_0,
    Sherif_2_1,
    Taiasha_0_0,
    Taiasha_0_1,
    Taiasha_1_0,
    Taiasha_1_1,
    Taiasha_2_0,
    Taiasha_2_1,
    Taiasha_3_0,
    Taiasha_3_1,
    Taiasha_4_0,
    Taiasha_4_1,
    Taiasha_5_0,
    Taiasha_5_1,
    Taiasha_6_0,
    Taiasha_6_1,
    JaalinI_0_0,
    JaalinI_0_1,
    JaalinI_1_0,
    JaalinI_1_1,
    JaalinI_2_0,
    JaalinI_2_1,
    JaalinI_3_0,
    JaalinI_3_1,
    JaalinI_4_0,
    JaalinI_4_1,
    JaalinI_5_0,
    JaalinI_5_1,
    JaalinI_6_0,
    JaalinI_6_1,
    MulazminI_0_0,
    MulazminI_0_1,
    MulazminI_1_0,
    MulazminI_1_1,
    MulazminI_2_0,
    MulazminI_2_1,
    MulazminI_3_0,
    MulazminI_3_1,
    MulazminI_4_0,
    MulazminI_4_1,
    MulazminI_5_0,
    MulazminI_5_1,
    MulazminI_6_0,
    MulazminI_6_1,
    MulazminI_7_0,
    MulazminI_7_1,
    Yakub_0_0,
}

impl UnitId {
    /// Map back to the `(section_name, col, row)` that this ID represents.
    #[must_use]
    pub fn section_pos(self) -> (SectionName, u8, u8) {
        match self {
            UnitId::AliWadHelu_0_0 => (SectionName::AliWadHelu, 0, 0),
            UnitId::AliWadHelu_0_1 => (SectionName::AliWadHelu, 0, 1),
            UnitId::AliWadHelu_1_0 => (SectionName::AliWadHelu, 1, 0),
            UnitId::AliWadHelu_1_1 => (SectionName::AliWadHelu, 1, 1),
            UnitId::AliWadHelu_2_0 => (SectionName::AliWadHelu, 2, 0),
            UnitId::AliWadHelu_2_1 => (SectionName::AliWadHelu, 2, 1),
            UnitId::AliWadHelu_3_0 => (SectionName::AliWadHelu, 3, 0),
            UnitId::AliWadHelu_3_1 => (SectionName::AliWadHelu, 3, 1),
            UnitId::AliWadHelu_4_0 => (SectionName::AliWadHelu, 4, 0),
            UnitId::AliWadHelu_4_1 => (SectionName::AliWadHelu, 4, 1),
            UnitId::AliWadHelu_5_0 => (SectionName::AliWadHelu, 5, 0),
            UnitId::AliWadHelu_5_1 => (SectionName::AliWadHelu, 5, 1),
            UnitId::Baggara_0_0 => (SectionName::Baggara, 0, 0),
            UnitId::Baggara_0_1 => (SectionName::Baggara, 0, 1),
            UnitId::Baggara_1_0 => (SectionName::Baggara, 1, 0),
            UnitId::Baggara_1_1 => (SectionName::Baggara, 1, 1),
            UnitId::Baggara_2_0 => (SectionName::Baggara, 2, 0),
            UnitId::Baggara_2_1 => (SectionName::Baggara, 2, 1),
            UnitId::Baggara_3_0 => (SectionName::Baggara, 3, 0),
            UnitId::Baggara_3_1 => (SectionName::Baggara, 3, 1),
            UnitId::Baggara_4_0 => (SectionName::Baggara, 4, 0),
            UnitId::Baggara_4_1 => (SectionName::Baggara, 4, 1),
            UnitId::Baggara_5_0 => (SectionName::Baggara, 5, 0),
            UnitId::Baggara_5_1 => (SectionName::Baggara, 5, 1),
            UnitId::BritishBoats_3_0 => (SectionName::BritishBoats, 3, 0),
            // (BritishBoats, 3, 1) is the single "Gen. Gordon" counter. The
            // `Gordon` alias variant was removed: two ids on one section
            // position meant two deployment candidates for one physical unit
            // (§9.346 checks the identity, not the id, so they were
            // interchangeable everywhere else).
            UnitId::BritishBoats_3_1 => (SectionName::BritishBoats, 3, 1),
            UnitId::BritishBoats_4_0 => (SectionName::BritishBoats, 4, 0),
            UnitId::BritishBoats_4_1 => (SectionName::BritishBoats, 4, 1),
            UnitId::BritishBoats_5_0 => (SectionName::BritishBoats, 5, 0),
            UnitId::BritishBoats_5_1 => (SectionName::BritishBoats, 5, 1),
            UnitId::BritishBoats_6_0 => (SectionName::BritishBoats, 6, 0),
            UnitId::BritishBoats_6_1 => (SectionName::BritishBoats, 6, 1),
            UnitId::BritishBoats_7_0 => (SectionName::BritishBoats, 7, 0),
            UnitId::BritishBoats_7_1 => (SectionName::BritishBoats, 7, 1),
            UnitId::BritishArmy_0_0 => (SectionName::BritishArmy, 0, 0),
            UnitId::BritishArmy_0_1 => (SectionName::BritishArmy, 0, 1),
            UnitId::BritishArmy_1_0 => (SectionName::BritishArmy, 1, 0),
            UnitId::BritishArmy_1_1 => (SectionName::BritishArmy, 1, 1),
            UnitId::BritishArmy_2_0 => (SectionName::BritishArmy, 2, 0),
            UnitId::BritishArmy_2_1 => (SectionName::BritishArmy, 2, 1),
            UnitId::BritishArmy_3_0 => (SectionName::BritishArmy, 3, 0),
            UnitId::BritishArmy_3_1 => (SectionName::BritishArmy, 3, 1),
            UnitId::BritishArmy_4_0 => (SectionName::BritishArmy, 4, 0),
            UnitId::BritishArmy_4_1 => (SectionName::BritishArmy, 4, 1),
            UnitId::BritishArmy_5_0 => (SectionName::BritishArmy, 5, 0),
            UnitId::BritishArmy_5_1 => (SectionName::BritishArmy, 5, 1),
            UnitId::BritishArmy_6_0 => (SectionName::BritishArmy, 6, 0),
            UnitId::BritishArmy_6_1 => (SectionName::BritishArmy, 6, 1),
            UnitId::BritishArmy_7_0 => (SectionName::BritishArmy, 7, 0),
            UnitId::BritishArmy_7_1 => (SectionName::BritishArmy, 7, 1),
            UnitId::Danagla_0_0 => (SectionName::Danagla, 0, 0),
            UnitId::Degheim_0_0 => (SectionName::Degheim, 0, 0),
            UnitId::Degheim_0_1 => (SectionName::Degheim, 0, 1),
            UnitId::Degheim_0_2 => (SectionName::Degheim, 0, 2),
            UnitId::Degheim_0_3 => (SectionName::Degheim, 0, 3),
            UnitId::Degheim_0_4 => (SectionName::Degheim, 0, 4),
            UnitId::EgyptianArmy_0_0 => (SectionName::EgyptianArmy, 0, 0),
            UnitId::EgyptianArmy_0_1 => (SectionName::EgyptianArmy, 0, 1),
            UnitId::EgyptianArmy_1_0 => (SectionName::EgyptianArmy, 1, 0),
            UnitId::EgyptianArmy_1_1 => (SectionName::EgyptianArmy, 1, 1),
            UnitId::EgyptianArmy_2_0 => (SectionName::EgyptianArmy, 2, 0),
            UnitId::EgyptianArmy_2_1 => (SectionName::EgyptianArmy, 2, 1),
            UnitId::EgyptianArmy_3_0 => (SectionName::EgyptianArmy, 3, 0),
            UnitId::EgyptianArmy_3_1 => (SectionName::EgyptianArmy, 3, 1),
            UnitId::EgyptianArmy_4_0 => (SectionName::EgyptianArmy, 4, 0),
            UnitId::EgyptianArmy_4_1 => (SectionName::EgyptianArmy, 4, 1),
            UnitId::EgyptianArmy_5_0 => (SectionName::EgyptianArmy, 5, 0),
            UnitId::EgyptianArmy_5_1 => (SectionName::EgyptianArmy, 5, 1),
            UnitId::EgyptianArmy_6_0 => (SectionName::EgyptianArmy, 6, 0),
            UnitId::EgyptianArmy_6_1 => (SectionName::EgyptianArmy, 6, 1),
            UnitId::EgyptianArmy_7_0 => (SectionName::EgyptianArmy, 7, 0),
            UnitId::EgyptianArmy_7_1 => (SectionName::EgyptianArmy, 7, 1),
            UnitId::Hadendowa_0_0 => (SectionName::Hadendowa, 0, 0),
            UnitId::Hadendowa_0_1 => (SectionName::Hadendowa, 0, 1),
            UnitId::Hadendowa_1_0 => (SectionName::Hadendowa, 1, 0),
            UnitId::Hadendowa_1_1 => (SectionName::Hadendowa, 1, 1),
            UnitId::Hadendowa_2_0 => (SectionName::Hadendowa, 2, 0),
            UnitId::Hadendowa_2_1 => (SectionName::Hadendowa, 2, 1),
            UnitId::Hadendowa_3_0 => (SectionName::Hadendowa, 3, 0),
            UnitId::Hadendowa_3_1 => (SectionName::Hadendowa, 3, 1),
            UnitId::Hadendowa_4_0 => (SectionName::Hadendowa, 4, 0),
            UnitId::Hadendowa_4_1 => (SectionName::Hadendowa, 4, 1),
            UnitId::Hadendowa_5_0 => (SectionName::Hadendowa, 5, 0),
            UnitId::Hadendowa_5_1 => (SectionName::Hadendowa, 5, 1),
            UnitId::Hadendowa_6_0 => (SectionName::Hadendowa, 6, 0),
            UnitId::Hadendowa_6_1 => (SectionName::Hadendowa, 6, 1),
            UnitId::Hadendowa_7_0 => (SectionName::Hadendowa, 7, 0),
            UnitId::Hadendowa_7_1 => (SectionName::Hadendowa, 7, 1),
            UnitId::HadendowaForts_0_0 => (SectionName::HadendowaForts, 0, 0),
            UnitId::HadendowaForts_0_1 => (SectionName::HadendowaForts, 0, 1),
            UnitId::HadendowaForts_1_0 => (SectionName::HadendowaForts, 1, 0),
            UnitId::HadendowaForts_1_1 => (SectionName::HadendowaForts, 1, 1),
            UnitId::HadendowaForts_2_0 => (SectionName::HadendowaForts, 2, 0),
            UnitId::HadendowaForts_2_1 => (SectionName::HadendowaForts, 2, 1),
            UnitId::HadendowaForts_3_0 => (SectionName::HadendowaForts, 3, 0),
            UnitId::HadendowaForts_3_1 => (SectionName::HadendowaForts, 3, 1),
            UnitId::HadendowaForts_4_0 => (SectionName::HadendowaForts, 4, 0),
            UnitId::HadendowaForts_4_1 => (SectionName::HadendowaForts, 4, 1),
            UnitId::HadendowaForts_5_0 => (SectionName::HadendowaForts, 5, 0),
            UnitId::HadendowaForts_5_1 => (SectionName::HadendowaForts, 5, 1),
            UnitId::HadendowaForts_6_0 => (SectionName::HadendowaForts, 6, 0),
            UnitId::HadendowaForts_6_1 => (SectionName::HadendowaForts, 6, 1),
            UnitId::HadendowaForts_7_0 => (SectionName::HadendowaForts, 7, 0),
            UnitId::HadendowaForts_7_1 => (SectionName::HadendowaForts, 7, 1),
            UnitId::Jehadia_0_0 => (SectionName::Jehadia, 0, 0),
            UnitId::Jehadia_0_1 => (SectionName::Jehadia, 0, 1),
            UnitId::Jehadia_1_0 => (SectionName::Jehadia, 1, 0),
            UnitId::Jehadia_1_1 => (SectionName::Jehadia, 1, 1),
            UnitId::Jehadia_2_0 => (SectionName::Jehadia, 2, 0),
            UnitId::Jehadia_2_1 => (SectionName::Jehadia, 2, 1),
            UnitId::Jehadia_3_0 => (SectionName::Jehadia, 3, 0),
            UnitId::Jehadia_3_1 => (SectionName::Jehadia, 3, 1),
            UnitId::Jehadia_4_0 => (SectionName::Jehadia, 4, 0),
            UnitId::Jehadia_4_1 => (SectionName::Jehadia, 4, 1),
            UnitId::Jehadia_5_0 => (SectionName::Jehadia, 5, 0),
            UnitId::Kehena_0_0 => (SectionName::Kehena, 0, 0),
            UnitId::Kehena_0_1 => (SectionName::Kehena, 0, 1),
            UnitId::Kehena_0_2 => (SectionName::Kehena, 0, 2),
            UnitId::Kehena_0_3 => (SectionName::Kehena, 0, 3),
            UnitId::Kehena_0_4 => (SectionName::Kehena, 0, 4),
            UnitId::Kehena_0_5 => (SectionName::Kehena, 0, 5),
            UnitId::KhalifaAbdullah_0_0 => (SectionName::KhalifaAbdullah, 0, 0),
            UnitId::KhalifaAbdullah_0_1 => (SectionName::KhalifaAbdullah, 0, 1),
            UnitId::KhalifaAbdullah_1_0 => (SectionName::KhalifaAbdullah, 1, 0),
            UnitId::KhalifaAbdullah_1_1 => (SectionName::KhalifaAbdullah, 1, 1),
            UnitId::KhalifaAbdullah_2_0 => (SectionName::KhalifaAbdullah, 2, 0),
            UnitId::KhalifaAbdullah_2_1 => (SectionName::KhalifaAbdullah, 2, 1),
            UnitId::Kitchener_0_0 => (SectionName::Kitchener, 0, 0),
            UnitId::Kitchener_0_1 => (SectionName::Kitchener, 0, 1),
            UnitId::Kitchener_1_0 => (SectionName::Kitchener, 1, 0),
            UnitId::Kitchener_1_1 => (SectionName::Kitchener, 1, 1),
            UnitId::Kitchener_2_0 => (SectionName::Kitchener, 2, 0),
            UnitId::Kitchener_2_1 => (SectionName::Kitchener, 2, 1),
            UnitId::Kitchener_3_0 => (SectionName::Kitchener, 3, 0),
            UnitId::Kitchener_3_1 => (SectionName::Kitchener, 3, 1),
            UnitId::Kitchener_4_0 => (SectionName::Kitchener, 4, 0),
            UnitId::Kitchener_4_1 => (SectionName::Kitchener, 4, 1),
            UnitId::Kitchener_5_0 => (SectionName::Kitchener, 5, 0),
            UnitId::Kitchener_5_1 => (SectionName::Kitchener, 5, 1),
            UnitId::Kitchener_6_0 => (SectionName::Kitchener, 6, 0),
            UnitId::Kitchener_6_1 => (SectionName::Kitchener, 6, 1),
            UnitId::Kitchener_7_0 => (SectionName::Kitchener, 7, 0),
            UnitId::Kitchener_7_1 => (SectionName::Kitchener, 7, 1),
            UnitId::JaalinII_0_0 => (SectionName::JaalinII, 0, 0),
            UnitId::JaalinII_0_1 => (SectionName::JaalinII, 0, 1),
            UnitId::JaalinII_1_0 => (SectionName::JaalinII, 1, 0),
            UnitId::JaalinII_1_1 => (SectionName::JaalinII, 1, 1),
            UnitId::JaalinII_2_0 => (SectionName::JaalinII, 2, 0),
            UnitId::JaalinII_2_1 => (SectionName::JaalinII, 2, 1),
            UnitId::JaalinII_3_0 => (SectionName::JaalinII, 3, 0),
            UnitId::JaalinII_3_1 => (SectionName::JaalinII, 3, 1),
            UnitId::JaalinII_4_0 => (SectionName::JaalinII, 4, 0),
            UnitId::JaalinII_4_1 => (SectionName::JaalinII, 4, 1),
            UnitId::JaalinII_5_0 => (SectionName::JaalinII, 5, 0),
            UnitId::JaalinII_5_1 => (SectionName::JaalinII, 5, 1),
            UnitId::MulazminII_0_0 => (SectionName::MulazminII, 0, 0),
            UnitId::MulazminII_0_1 => (SectionName::MulazminII, 0, 1),
            UnitId::MulazminII_1_0 => (SectionName::MulazminII, 1, 0),
            UnitId::MulazminII_1_1 => (SectionName::MulazminII, 1, 1),
            UnitId::MulazminII_2_0 => (SectionName::MulazminII, 2, 0),
            UnitId::MulazminII_2_1 => (SectionName::MulazminII, 2, 1),
            UnitId::MulazminII_3_0 => (SectionName::MulazminII, 3, 0),
            UnitId::MulazminII_3_1 => (SectionName::MulazminII, 3, 1),
            UnitId::MulazminII_4_0 => (SectionName::MulazminII, 4, 0),
            UnitId::MulazminII_4_1 => (SectionName::MulazminII, 4, 1),
            UnitId::MulazminII_5_0 => (SectionName::MulazminII, 5, 0),
            UnitId::MulazminII_5_1 => (SectionName::MulazminII, 5, 1),
            UnitId::MulazminII_6_0 => (SectionName::MulazminII, 6, 0),
            UnitId::MulazminII_6_1 => (SectionName::MulazminII, 6, 1),
            UnitId::MulazminII_7_0 => (SectionName::MulazminII, 7, 0),
            UnitId::MulazminII_7_1 => (SectionName::MulazminII, 7, 1),
            UnitId::Mulazmin_0_0 => (SectionName::Mulazmin, 0, 0),
            UnitId::OsmanDigna_0_0 => (SectionName::OsmanDigna, 0, 0),
            UnitId::SheikElDin_0_0 => (SectionName::SheikElDin, 0, 0),
            UnitId::SheikElDin_0_1 => (SectionName::SheikElDin, 0, 1),
            UnitId::SheikElDin_1_0 => (SectionName::SheikElDin, 1, 0),
            UnitId::SheikElDin_1_1 => (SectionName::SheikElDin, 1, 1),
            UnitId::SheikElDin_2_0 => (SectionName::SheikElDin, 2, 0),
            UnitId::SheikElDin_2_1 => (SectionName::SheikElDin, 2, 1),
            UnitId::SheikElDin_3_0 => (SectionName::SheikElDin, 3, 0),
            UnitId::SheikElDin_3_1 => (SectionName::SheikElDin, 3, 1),
            UnitId::SheikElDin_4_0 => (SectionName::SheikElDin, 4, 0),
            UnitId::SheikElDin_4_1 => (SectionName::SheikElDin, 4, 1),
            UnitId::SheikElDin_5_0 => (SectionName::SheikElDin, 5, 0),
            UnitId::SheikElDin_5_1 => (SectionName::SheikElDin, 5, 1),
            UnitId::SheikElDin_6_0 => (SectionName::SheikElDin, 6, 0),
            UnitId::SheikElDin_6_1 => (SectionName::SheikElDin, 6, 1),
            UnitId::Sherif_0_0 => (SectionName::Sherif, 0, 0),
            UnitId::Sherif_1_0 => (SectionName::Sherif, 1, 0),
            UnitId::Sherif_1_1 => (SectionName::Sherif, 1, 1),
            UnitId::Sherif_2_0 => (SectionName::Sherif, 2, 0),
            UnitId::Sherif_2_1 => (SectionName::Sherif, 2, 1),
            UnitId::Taiasha_0_0 => (SectionName::Taiasha, 0, 0),
            UnitId::Taiasha_0_1 => (SectionName::Taiasha, 0, 1),
            UnitId::Taiasha_1_0 => (SectionName::Taiasha, 1, 0),
            UnitId::Taiasha_1_1 => (SectionName::Taiasha, 1, 1),
            UnitId::Taiasha_2_0 => (SectionName::Taiasha, 2, 0),
            UnitId::Taiasha_2_1 => (SectionName::Taiasha, 2, 1),
            UnitId::Taiasha_3_0 => (SectionName::Taiasha, 3, 0),
            UnitId::Taiasha_3_1 => (SectionName::Taiasha, 3, 1),
            UnitId::Taiasha_4_0 => (SectionName::Taiasha, 4, 0),
            UnitId::Taiasha_4_1 => (SectionName::Taiasha, 4, 1),
            UnitId::Taiasha_5_0 => (SectionName::Taiasha, 5, 0),
            UnitId::Taiasha_5_1 => (SectionName::Taiasha, 5, 1),
            UnitId::Taiasha_6_0 => (SectionName::Taiasha, 6, 0),
            UnitId::Taiasha_6_1 => (SectionName::Taiasha, 6, 1),
            UnitId::JaalinI_0_0 => (SectionName::JaalinI, 0, 0),
            UnitId::JaalinI_0_1 => (SectionName::JaalinI, 0, 1),
            UnitId::JaalinI_1_0 => (SectionName::JaalinI, 1, 0),
            UnitId::JaalinI_1_1 => (SectionName::JaalinI, 1, 1),
            UnitId::JaalinI_2_0 => (SectionName::JaalinI, 2, 0),
            UnitId::JaalinI_2_1 => (SectionName::JaalinI, 2, 1),
            UnitId::JaalinI_3_0 => (SectionName::JaalinI, 3, 0),
            UnitId::JaalinI_3_1 => (SectionName::JaalinI, 3, 1),
            UnitId::JaalinI_4_0 => (SectionName::JaalinI, 4, 0),
            UnitId::JaalinI_4_1 => (SectionName::JaalinI, 4, 1),
            UnitId::JaalinI_5_0 => (SectionName::JaalinI, 5, 0),
            UnitId::JaalinI_5_1 => (SectionName::JaalinI, 5, 1),
            UnitId::JaalinI_6_0 => (SectionName::JaalinI, 6, 0),
            UnitId::JaalinI_6_1 => (SectionName::JaalinI, 6, 1),
            UnitId::MulazminI_0_0 => (SectionName::MulazminI, 0, 0),
            UnitId::MulazminI_0_1 => (SectionName::MulazminI, 0, 1),
            UnitId::MulazminI_1_0 => (SectionName::MulazminI, 1, 0),
            UnitId::MulazminI_1_1 => (SectionName::MulazminI, 1, 1),
            UnitId::MulazminI_2_0 => (SectionName::MulazminI, 2, 0),
            UnitId::MulazminI_2_1 => (SectionName::MulazminI, 2, 1),
            UnitId::MulazminI_3_0 => (SectionName::MulazminI, 3, 0),
            UnitId::MulazminI_3_1 => (SectionName::MulazminI, 3, 1),
            UnitId::MulazminI_4_0 => (SectionName::MulazminI, 4, 0),
            UnitId::MulazminI_4_1 => (SectionName::MulazminI, 4, 1),
            UnitId::MulazminI_5_0 => (SectionName::MulazminI, 5, 0),
            UnitId::MulazminI_5_1 => (SectionName::MulazminI, 5, 1),
            UnitId::MulazminI_6_0 => (SectionName::MulazminI, 6, 0),
            UnitId::MulazminI_6_1 => (SectionName::MulazminI, 6, 1),
            UnitId::MulazminI_7_0 => (SectionName::MulazminI, 7, 0),
            UnitId::MulazminI_7_1 => (SectionName::MulazminI, 7, 1),
            UnitId::Yakub_0_0 => (SectionName::Yakub, 0, 0),
        }
    }

    /// All valid unit IDs.
    pub const ALL: &'static [Self] = &[
        Self::AliWadHelu_0_0,
        Self::AliWadHelu_0_1,
        Self::AliWadHelu_1_0,
        Self::AliWadHelu_1_1,
        Self::AliWadHelu_2_0,
        Self::AliWadHelu_2_1,
        Self::AliWadHelu_3_0,
        Self::AliWadHelu_3_1,
        Self::AliWadHelu_4_0,
        Self::AliWadHelu_4_1,
        Self::AliWadHelu_5_0,
        Self::AliWadHelu_5_1,
        Self::Baggara_0_0,
        Self::Baggara_0_1,
        Self::Baggara_1_0,
        Self::Baggara_1_1,
        Self::Baggara_2_0,
        Self::Baggara_2_1,
        Self::Baggara_3_0,
        Self::Baggara_3_1,
        Self::Baggara_4_0,
        Self::Baggara_4_1,
        Self::Baggara_5_0,
        Self::Baggara_5_1,
        Self::BritishBoats_3_0,
        Self::BritishBoats_3_1,
        Self::BritishBoats_4_0,
        Self::BritishBoats_4_1,
        Self::BritishBoats_5_0,
        Self::BritishBoats_5_1,
        Self::BritishBoats_6_0,
        Self::BritishBoats_6_1,
        Self::BritishBoats_7_0,
        Self::BritishBoats_7_1,
        Self::BritishArmy_0_0,
        Self::BritishArmy_0_1,
        Self::BritishArmy_1_0,
        Self::BritishArmy_1_1,
        Self::BritishArmy_2_0,
        Self::BritishArmy_2_1,
        Self::BritishArmy_3_0,
        Self::BritishArmy_3_1,
        Self::BritishArmy_4_0,
        Self::BritishArmy_4_1,
        Self::BritishArmy_5_0,
        Self::BritishArmy_5_1,
        Self::BritishArmy_6_0,
        Self::BritishArmy_6_1,
        Self::BritishArmy_7_0,
        Self::BritishArmy_7_1,
        Self::Danagla_0_0,
        Self::Degheim_0_0,
        Self::Degheim_0_1,
        Self::Degheim_0_2,
        Self::Degheim_0_3,
        Self::Degheim_0_4,
        Self::EgyptianArmy_0_0,
        Self::EgyptianArmy_0_1,
        Self::EgyptianArmy_1_0,
        Self::EgyptianArmy_1_1,
        Self::EgyptianArmy_2_0,
        Self::EgyptianArmy_2_1,
        Self::EgyptianArmy_3_0,
        Self::EgyptianArmy_3_1,
        Self::EgyptianArmy_4_0,
        Self::EgyptianArmy_4_1,
        Self::EgyptianArmy_5_0,
        Self::EgyptianArmy_5_1,
        Self::EgyptianArmy_6_0,
        Self::EgyptianArmy_6_1,
        Self::EgyptianArmy_7_0,
        Self::EgyptianArmy_7_1,
        Self::Hadendowa_0_0,
        Self::Hadendowa_0_1,
        Self::Hadendowa_1_0,
        Self::Hadendowa_1_1,
        Self::Hadendowa_2_0,
        Self::Hadendowa_2_1,
        Self::Hadendowa_3_0,
        Self::Hadendowa_3_1,
        Self::Hadendowa_4_0,
        Self::Hadendowa_4_1,
        Self::Hadendowa_5_0,
        Self::Hadendowa_5_1,
        Self::Hadendowa_6_0,
        Self::Hadendowa_6_1,
        Self::Hadendowa_7_0,
        Self::Hadendowa_7_1,
        Self::HadendowaForts_0_0,
        Self::HadendowaForts_0_1,
        Self::HadendowaForts_1_0,
        Self::HadendowaForts_1_1,
        Self::HadendowaForts_2_0,
        Self::HadendowaForts_2_1,
        Self::HadendowaForts_3_0,
        Self::HadendowaForts_3_1,
        Self::HadendowaForts_4_0,
        Self::HadendowaForts_4_1,
        Self::HadendowaForts_5_0,
        Self::HadendowaForts_5_1,
        Self::HadendowaForts_6_0,
        Self::HadendowaForts_6_1,
        Self::HadendowaForts_7_0,
        Self::HadendowaForts_7_1,
        Self::Jehadia_0_0,
        Self::Jehadia_0_1,
        Self::Jehadia_1_0,
        Self::Jehadia_1_1,
        Self::Jehadia_2_0,
        Self::Jehadia_2_1,
        Self::Jehadia_3_0,
        Self::Jehadia_3_1,
        Self::Jehadia_4_0,
        Self::Jehadia_4_1,
        Self::Jehadia_5_0,
        Self::Kehena_0_0,
        Self::Kehena_0_1,
        Self::Kehena_0_2,
        Self::Kehena_0_3,
        Self::Kehena_0_4,
        Self::Kehena_0_5,
        Self::KhalifaAbdullah_0_0,
        Self::KhalifaAbdullah_0_1,
        Self::KhalifaAbdullah_1_0,
        Self::KhalifaAbdullah_1_1,
        Self::KhalifaAbdullah_2_0,
        Self::KhalifaAbdullah_2_1,
        Self::Kitchener_0_0,
        Self::Kitchener_0_1,
        Self::Kitchener_1_0,
        Self::Kitchener_1_1,
        Self::Kitchener_2_0,
        Self::Kitchener_2_1,
        Self::Kitchener_3_0,
        Self::Kitchener_3_1,
        Self::Kitchener_4_0,
        Self::Kitchener_4_1,
        Self::Kitchener_5_0,
        Self::Kitchener_5_1,
        Self::Kitchener_6_0,
        Self::Kitchener_6_1,
        Self::Kitchener_7_0,
        Self::Kitchener_7_1,
        Self::JaalinII_0_0,
        Self::JaalinII_0_1,
        Self::JaalinII_1_0,
        Self::JaalinII_1_1,
        Self::JaalinII_2_0,
        Self::JaalinII_2_1,
        Self::JaalinII_3_0,
        Self::JaalinII_3_1,
        Self::JaalinII_4_0,
        Self::JaalinII_4_1,
        Self::JaalinII_5_0,
        Self::JaalinII_5_1,
        Self::MulazminII_0_0,
        Self::MulazminII_0_1,
        Self::MulazminII_1_0,
        Self::MulazminII_1_1,
        Self::MulazminII_2_0,
        Self::MulazminII_2_1,
        Self::MulazminII_3_0,
        Self::MulazminII_3_1,
        Self::MulazminII_4_0,
        Self::MulazminII_4_1,
        Self::MulazminII_5_0,
        Self::MulazminII_5_1,
        Self::MulazminII_6_0,
        Self::MulazminII_6_1,
        Self::MulazminII_7_0,
        Self::MulazminII_7_1,
        Self::Mulazmin_0_0,
        Self::OsmanDigna_0_0,
        Self::SheikElDin_0_0,
        Self::SheikElDin_0_1,
        Self::SheikElDin_1_0,
        Self::SheikElDin_1_1,
        Self::SheikElDin_2_0,
        Self::SheikElDin_2_1,
        Self::SheikElDin_3_0,
        Self::SheikElDin_3_1,
        Self::SheikElDin_4_0,
        Self::SheikElDin_4_1,
        Self::SheikElDin_5_0,
        Self::SheikElDin_5_1,
        Self::SheikElDin_6_0,
        Self::SheikElDin_6_1,
        Self::Sherif_0_0,
        Self::Sherif_1_0,
        Self::Sherif_1_1,
        Self::Sherif_2_0,
        Self::Sherif_2_1,
        Self::Taiasha_0_0,
        Self::Taiasha_0_1,
        Self::Taiasha_1_0,
        Self::Taiasha_1_1,
        Self::Taiasha_2_0,
        Self::Taiasha_2_1,
        Self::Taiasha_3_0,
        Self::Taiasha_3_1,
        Self::Taiasha_4_0,
        Self::Taiasha_4_1,
        Self::Taiasha_5_0,
        Self::Taiasha_5_1,
        Self::Taiasha_6_0,
        Self::Taiasha_6_1,
        Self::JaalinI_0_0,
        Self::JaalinI_0_1,
        Self::JaalinI_1_0,
        Self::JaalinI_1_1,
        Self::JaalinI_2_0,
        Self::JaalinI_2_1,
        Self::JaalinI_3_0,
        Self::JaalinI_3_1,
        Self::JaalinI_4_0,
        Self::JaalinI_4_1,
        Self::JaalinI_5_0,
        Self::JaalinI_5_1,
        Self::JaalinI_6_0,
        Self::JaalinI_6_1,
        Self::MulazminI_0_0,
        Self::MulazminI_0_1,
        Self::MulazminI_1_0,
        Self::MulazminI_1_1,
        Self::MulazminI_2_0,
        Self::MulazminI_2_1,
        Self::MulazminI_3_0,
        Self::MulazminI_3_1,
        Self::MulazminI_4_0,
        Self::MulazminI_4_1,
        Self::MulazminI_5_0,
        Self::MulazminI_5_1,
        Self::MulazminI_6_0,
        Self::MulazminI_6_1,
        Self::MulazminI_7_0,
        Self::MulazminI_7_1,
        Self::Yakub_0_0,
    ];

    /// The faction of this unit, from the annotations data.
    #[must_use]
    pub fn faction(self) -> Option<omdurman_types::Faction> {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r).and_then(|d| d.faction)
    }

    /// The [`UnitKind`](omdurman_types::UnitKind) of this unit, from the annotations data.
    #[must_use]
    pub fn kind(self) -> Option<omdurman_types::UnitKind> {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r).and_then(|d| d.kind)
    }

    /// The [`SpriteColor`](omdurman_types::SpriteColor) of this unit's sprite.
    #[must_use]
    pub fn color(self) -> omdurman_types::SpriteColor {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.color)
            .unwrap_or(omdurman_types::SpriteColor::SandBlack)
    }

    /// The display text of this unit's sprite.
    #[must_use]
    pub fn text(self) -> &'static str {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.text)
            .unwrap_or("")
    }
}

/// Look up the [`UnitId`] for a given sprite-sheet position.
#[must_use]
pub fn unit_id_for_section_pos(section: SectionName, col: u8, row: u8) -> Option<UnitId> {
    match (section, col, row) {
        (SectionName::AliWadHelu, 0, 0) => Some(UnitId::AliWadHelu_0_0),
        (SectionName::AliWadHelu, 0, 1) => Some(UnitId::AliWadHelu_0_1),
        (SectionName::AliWadHelu, 1, 0) => Some(UnitId::AliWadHelu_1_0),
        (SectionName::AliWadHelu, 1, 1) => Some(UnitId::AliWadHelu_1_1),
        (SectionName::AliWadHelu, 2, 0) => Some(UnitId::AliWadHelu_2_0),
        (SectionName::AliWadHelu, 2, 1) => Some(UnitId::AliWadHelu_2_1),
        (SectionName::AliWadHelu, 3, 0) => Some(UnitId::AliWadHelu_3_0),
        (SectionName::AliWadHelu, 3, 1) => Some(UnitId::AliWadHelu_3_1),
        (SectionName::AliWadHelu, 4, 0) => Some(UnitId::AliWadHelu_4_0),
        (SectionName::AliWadHelu, 4, 1) => Some(UnitId::AliWadHelu_4_1),
        (SectionName::AliWadHelu, 5, 0) => Some(UnitId::AliWadHelu_5_0),
        (SectionName::AliWadHelu, 5, 1) => Some(UnitId::AliWadHelu_5_1),
        (SectionName::Baggara, 0, 0) => Some(UnitId::Baggara_0_0),
        (SectionName::Baggara, 0, 1) => Some(UnitId::Baggara_0_1),
        (SectionName::Baggara, 1, 0) => Some(UnitId::Baggara_1_0),
        (SectionName::Baggara, 1, 1) => Some(UnitId::Baggara_1_1),
        (SectionName::Baggara, 2, 0) => Some(UnitId::Baggara_2_0),
        (SectionName::Baggara, 2, 1) => Some(UnitId::Baggara_2_1),
        (SectionName::Baggara, 3, 0) => Some(UnitId::Baggara_3_0),
        (SectionName::Baggara, 3, 1) => Some(UnitId::Baggara_3_1),
        (SectionName::Baggara, 4, 0) => Some(UnitId::Baggara_4_0),
        (SectionName::Baggara, 4, 1) => Some(UnitId::Baggara_4_1),
        (SectionName::Baggara, 5, 0) => Some(UnitId::Baggara_5_0),
        (SectionName::Baggara, 5, 1) => Some(UnitId::Baggara_5_1),
        (SectionName::BritishBoats, 3, 0) => Some(UnitId::BritishBoats_3_0),
        (SectionName::BritishBoats, 3, 1) => Some(UnitId::BritishBoats_3_1),
        (SectionName::BritishBoats, 4, 0) => Some(UnitId::BritishBoats_4_0),
        (SectionName::BritishBoats, 4, 1) => Some(UnitId::BritishBoats_4_1),
        (SectionName::BritishBoats, 5, 0) => Some(UnitId::BritishBoats_5_0),
        (SectionName::BritishBoats, 5, 1) => Some(UnitId::BritishBoats_5_1),
        (SectionName::BritishBoats, 6, 0) => Some(UnitId::BritishBoats_6_0),
        (SectionName::BritishBoats, 6, 1) => Some(UnitId::BritishBoats_6_1),
        (SectionName::BritishBoats, 7, 0) => Some(UnitId::BritishBoats_7_0),
        (SectionName::BritishBoats, 7, 1) => Some(UnitId::BritishBoats_7_1),
        (SectionName::BritishArmy, 0, 0) => Some(UnitId::BritishArmy_0_0),
        (SectionName::BritishArmy, 0, 1) => Some(UnitId::BritishArmy_0_1),
        (SectionName::BritishArmy, 1, 0) => Some(UnitId::BritishArmy_1_0),
        (SectionName::BritishArmy, 1, 1) => Some(UnitId::BritishArmy_1_1),
        (SectionName::BritishArmy, 2, 0) => Some(UnitId::BritishArmy_2_0),
        (SectionName::BritishArmy, 2, 1) => Some(UnitId::BritishArmy_2_1),
        (SectionName::BritishArmy, 3, 0) => Some(UnitId::BritishArmy_3_0),
        (SectionName::BritishArmy, 3, 1) => Some(UnitId::BritishArmy_3_1),
        (SectionName::BritishArmy, 4, 0) => Some(UnitId::BritishArmy_4_0),
        (SectionName::BritishArmy, 4, 1) => Some(UnitId::BritishArmy_4_1),
        (SectionName::BritishArmy, 5, 0) => Some(UnitId::BritishArmy_5_0),
        (SectionName::BritishArmy, 5, 1) => Some(UnitId::BritishArmy_5_1),
        (SectionName::BritishArmy, 6, 0) => Some(UnitId::BritishArmy_6_0),
        (SectionName::BritishArmy, 6, 1) => Some(UnitId::BritishArmy_6_1),
        (SectionName::BritishArmy, 7, 0) => Some(UnitId::BritishArmy_7_0),
        (SectionName::BritishArmy, 7, 1) => Some(UnitId::BritishArmy_7_1),
        (SectionName::Danagla, 0, 0) => Some(UnitId::Danagla_0_0),
        (SectionName::Degheim, 0, 0) => Some(UnitId::Degheim_0_0),
        (SectionName::Degheim, 0, 1) => Some(UnitId::Degheim_0_1),
        (SectionName::Degheim, 0, 2) => Some(UnitId::Degheim_0_2),
        (SectionName::Degheim, 0, 3) => Some(UnitId::Degheim_0_3),
        (SectionName::Degheim, 0, 4) => Some(UnitId::Degheim_0_4),
        (SectionName::EgyptianArmy, 0, 0) => Some(UnitId::EgyptianArmy_0_0),
        (SectionName::EgyptianArmy, 0, 1) => Some(UnitId::EgyptianArmy_0_1),
        (SectionName::EgyptianArmy, 1, 0) => Some(UnitId::EgyptianArmy_1_0),
        (SectionName::EgyptianArmy, 1, 1) => Some(UnitId::EgyptianArmy_1_1),
        (SectionName::EgyptianArmy, 2, 0) => Some(UnitId::EgyptianArmy_2_0),
        (SectionName::EgyptianArmy, 2, 1) => Some(UnitId::EgyptianArmy_2_1),
        (SectionName::EgyptianArmy, 3, 0) => Some(UnitId::EgyptianArmy_3_0),
        (SectionName::EgyptianArmy, 3, 1) => Some(UnitId::EgyptianArmy_3_1),
        (SectionName::EgyptianArmy, 4, 0) => Some(UnitId::EgyptianArmy_4_0),
        (SectionName::EgyptianArmy, 4, 1) => Some(UnitId::EgyptianArmy_4_1),
        (SectionName::EgyptianArmy, 5, 0) => Some(UnitId::EgyptianArmy_5_0),
        (SectionName::EgyptianArmy, 5, 1) => Some(UnitId::EgyptianArmy_5_1),
        (SectionName::EgyptianArmy, 6, 0) => Some(UnitId::EgyptianArmy_6_0),
        (SectionName::EgyptianArmy, 6, 1) => Some(UnitId::EgyptianArmy_6_1),
        (SectionName::EgyptianArmy, 7, 0) => Some(UnitId::EgyptianArmy_7_0),
        (SectionName::EgyptianArmy, 7, 1) => Some(UnitId::EgyptianArmy_7_1),
        (SectionName::Hadendowa, 0, 0) => Some(UnitId::Hadendowa_0_0),
        (SectionName::Hadendowa, 0, 1) => Some(UnitId::Hadendowa_0_1),
        (SectionName::Hadendowa, 1, 0) => Some(UnitId::Hadendowa_1_0),
        (SectionName::Hadendowa, 1, 1) => Some(UnitId::Hadendowa_1_1),
        (SectionName::Hadendowa, 2, 0) => Some(UnitId::Hadendowa_2_0),
        (SectionName::Hadendowa, 2, 1) => Some(UnitId::Hadendowa_2_1),
        (SectionName::Hadendowa, 3, 0) => Some(UnitId::Hadendowa_3_0),
        (SectionName::Hadendowa, 3, 1) => Some(UnitId::Hadendowa_3_1),
        (SectionName::Hadendowa, 4, 0) => Some(UnitId::Hadendowa_4_0),
        (SectionName::Hadendowa, 4, 1) => Some(UnitId::Hadendowa_4_1),
        (SectionName::Hadendowa, 5, 0) => Some(UnitId::Hadendowa_5_0),
        (SectionName::Hadendowa, 5, 1) => Some(UnitId::Hadendowa_5_1),
        (SectionName::Hadendowa, 6, 0) => Some(UnitId::Hadendowa_6_0),
        (SectionName::Hadendowa, 6, 1) => Some(UnitId::Hadendowa_6_1),
        (SectionName::Hadendowa, 7, 0) => Some(UnitId::Hadendowa_7_0),
        (SectionName::Hadendowa, 7, 1) => Some(UnitId::Hadendowa_7_1),
        (SectionName::HadendowaForts, 0, 0) => Some(UnitId::HadendowaForts_0_0),
        (SectionName::HadendowaForts, 0, 1) => Some(UnitId::HadendowaForts_0_1),
        (SectionName::HadendowaForts, 1, 0) => Some(UnitId::HadendowaForts_1_0),
        (SectionName::HadendowaForts, 1, 1) => Some(UnitId::HadendowaForts_1_1),
        (SectionName::HadendowaForts, 2, 0) => Some(UnitId::HadendowaForts_2_0),
        (SectionName::HadendowaForts, 2, 1) => Some(UnitId::HadendowaForts_2_1),
        (SectionName::HadendowaForts, 3, 0) => Some(UnitId::HadendowaForts_3_0),
        (SectionName::HadendowaForts, 3, 1) => Some(UnitId::HadendowaForts_3_1),
        (SectionName::HadendowaForts, 4, 0) => Some(UnitId::HadendowaForts_4_0),
        (SectionName::HadendowaForts, 4, 1) => Some(UnitId::HadendowaForts_4_1),
        (SectionName::HadendowaForts, 5, 0) => Some(UnitId::HadendowaForts_5_0),
        (SectionName::HadendowaForts, 5, 1) => Some(UnitId::HadendowaForts_5_1),
        (SectionName::HadendowaForts, 6, 0) => Some(UnitId::HadendowaForts_6_0),
        (SectionName::HadendowaForts, 6, 1) => Some(UnitId::HadendowaForts_6_1),
        (SectionName::HadendowaForts, 7, 0) => Some(UnitId::HadendowaForts_7_0),
        (SectionName::HadendowaForts, 7, 1) => Some(UnitId::HadendowaForts_7_1),
        (SectionName::Jehadia, 0, 0) => Some(UnitId::Jehadia_0_0),
        (SectionName::Jehadia, 0, 1) => Some(UnitId::Jehadia_0_1),
        (SectionName::Jehadia, 1, 0) => Some(UnitId::Jehadia_1_0),
        (SectionName::Jehadia, 1, 1) => Some(UnitId::Jehadia_1_1),
        (SectionName::Jehadia, 2, 0) => Some(UnitId::Jehadia_2_0),
        (SectionName::Jehadia, 2, 1) => Some(UnitId::Jehadia_2_1),
        (SectionName::Jehadia, 3, 0) => Some(UnitId::Jehadia_3_0),
        (SectionName::Jehadia, 3, 1) => Some(UnitId::Jehadia_3_1),
        (SectionName::Jehadia, 4, 0) => Some(UnitId::Jehadia_4_0),
        (SectionName::Jehadia, 4, 1) => Some(UnitId::Jehadia_4_1),
        (SectionName::Jehadia, 5, 0) => Some(UnitId::Jehadia_5_0),
        (SectionName::Kehena, 0, 0) => Some(UnitId::Kehena_0_0),
        (SectionName::Kehena, 0, 1) => Some(UnitId::Kehena_0_1),
        (SectionName::Kehena, 0, 2) => Some(UnitId::Kehena_0_2),
        (SectionName::Kehena, 0, 3) => Some(UnitId::Kehena_0_3),
        (SectionName::Kehena, 0, 4) => Some(UnitId::Kehena_0_4),
        (SectionName::Kehena, 0, 5) => Some(UnitId::Kehena_0_5),
        (SectionName::KhalifaAbdullah, 0, 0) => Some(UnitId::KhalifaAbdullah_0_0),
        (SectionName::KhalifaAbdullah, 0, 1) => Some(UnitId::KhalifaAbdullah_0_1),
        (SectionName::KhalifaAbdullah, 1, 0) => Some(UnitId::KhalifaAbdullah_1_0),
        (SectionName::KhalifaAbdullah, 1, 1) => Some(UnitId::KhalifaAbdullah_1_1),
        (SectionName::KhalifaAbdullah, 2, 0) => Some(UnitId::KhalifaAbdullah_2_0),
        (SectionName::KhalifaAbdullah, 2, 1) => Some(UnitId::KhalifaAbdullah_2_1),
        (SectionName::Kitchener, 0, 0) => Some(UnitId::Kitchener_0_0),
        (SectionName::Kitchener, 0, 1) => Some(UnitId::Kitchener_0_1),
        (SectionName::Kitchener, 1, 0) => Some(UnitId::Kitchener_1_0),
        (SectionName::Kitchener, 1, 1) => Some(UnitId::Kitchener_1_1),
        (SectionName::Kitchener, 2, 0) => Some(UnitId::Kitchener_2_0),
        (SectionName::Kitchener, 2, 1) => Some(UnitId::Kitchener_2_1),
        (SectionName::Kitchener, 3, 0) => Some(UnitId::Kitchener_3_0),
        (SectionName::Kitchener, 3, 1) => Some(UnitId::Kitchener_3_1),
        (SectionName::Kitchener, 4, 0) => Some(UnitId::Kitchener_4_0),
        (SectionName::Kitchener, 4, 1) => Some(UnitId::Kitchener_4_1),
        (SectionName::Kitchener, 5, 0) => Some(UnitId::Kitchener_5_0),
        (SectionName::Kitchener, 5, 1) => Some(UnitId::Kitchener_5_1),
        (SectionName::Kitchener, 6, 0) => Some(UnitId::Kitchener_6_0),
        (SectionName::Kitchener, 6, 1) => Some(UnitId::Kitchener_6_1),
        (SectionName::Kitchener, 7, 0) => Some(UnitId::Kitchener_7_0),
        (SectionName::Kitchener, 7, 1) => Some(UnitId::Kitchener_7_1),
        (SectionName::JaalinII, 0, 0) => Some(UnitId::JaalinII_0_0),
        (SectionName::JaalinII, 0, 1) => Some(UnitId::JaalinII_0_1),
        (SectionName::JaalinII, 1, 0) => Some(UnitId::JaalinII_1_0),
        (SectionName::JaalinII, 1, 1) => Some(UnitId::JaalinII_1_1),
        (SectionName::JaalinII, 2, 0) => Some(UnitId::JaalinII_2_0),
        (SectionName::JaalinII, 2, 1) => Some(UnitId::JaalinII_2_1),
        (SectionName::JaalinII, 3, 0) => Some(UnitId::JaalinII_3_0),
        (SectionName::JaalinII, 3, 1) => Some(UnitId::JaalinII_3_1),
        (SectionName::JaalinII, 4, 0) => Some(UnitId::JaalinII_4_0),
        (SectionName::JaalinII, 4, 1) => Some(UnitId::JaalinII_4_1),
        (SectionName::JaalinII, 5, 0) => Some(UnitId::JaalinII_5_0),
        (SectionName::JaalinII, 5, 1) => Some(UnitId::JaalinII_5_1),
        (SectionName::MulazminII, 0, 0) => Some(UnitId::MulazminII_0_0),
        (SectionName::MulazminII, 0, 1) => Some(UnitId::MulazminII_0_1),
        (SectionName::MulazminII, 1, 0) => Some(UnitId::MulazminII_1_0),
        (SectionName::MulazminII, 1, 1) => Some(UnitId::MulazminII_1_1),
        (SectionName::MulazminII, 2, 0) => Some(UnitId::MulazminII_2_0),
        (SectionName::MulazminII, 2, 1) => Some(UnitId::MulazminII_2_1),
        (SectionName::MulazminII, 3, 0) => Some(UnitId::MulazminII_3_0),
        (SectionName::MulazminII, 3, 1) => Some(UnitId::MulazminII_3_1),
        (SectionName::MulazminII, 4, 0) => Some(UnitId::MulazminII_4_0),
        (SectionName::MulazminII, 4, 1) => Some(UnitId::MulazminII_4_1),
        (SectionName::MulazminII, 5, 0) => Some(UnitId::MulazminII_5_0),
        (SectionName::MulazminII, 5, 1) => Some(UnitId::MulazminII_5_1),
        (SectionName::MulazminII, 6, 0) => Some(UnitId::MulazminII_6_0),
        (SectionName::MulazminII, 6, 1) => Some(UnitId::MulazminII_6_1),
        (SectionName::MulazminII, 7, 0) => Some(UnitId::MulazminII_7_0),
        (SectionName::MulazminII, 7, 1) => Some(UnitId::MulazminII_7_1),
        (SectionName::Mulazmin, 0, 0) => Some(UnitId::Mulazmin_0_0),
        (SectionName::OsmanDigna, 0, 0) => Some(UnitId::OsmanDigna_0_0),
        (SectionName::SheikElDin, 0, 0) => Some(UnitId::SheikElDin_0_0),
        (SectionName::SheikElDin, 0, 1) => Some(UnitId::SheikElDin_0_1),
        (SectionName::SheikElDin, 1, 0) => Some(UnitId::SheikElDin_1_0),
        (SectionName::SheikElDin, 1, 1) => Some(UnitId::SheikElDin_1_1),
        (SectionName::SheikElDin, 2, 0) => Some(UnitId::SheikElDin_2_0),
        (SectionName::SheikElDin, 2, 1) => Some(UnitId::SheikElDin_2_1),
        (SectionName::SheikElDin, 3, 0) => Some(UnitId::SheikElDin_3_0),
        (SectionName::SheikElDin, 3, 1) => Some(UnitId::SheikElDin_3_1),
        (SectionName::SheikElDin, 4, 0) => Some(UnitId::SheikElDin_4_0),
        (SectionName::SheikElDin, 4, 1) => Some(UnitId::SheikElDin_4_1),
        (SectionName::SheikElDin, 5, 0) => Some(UnitId::SheikElDin_5_0),
        (SectionName::SheikElDin, 5, 1) => Some(UnitId::SheikElDin_5_1),
        (SectionName::SheikElDin, 6, 0) => Some(UnitId::SheikElDin_6_0),
        (SectionName::SheikElDin, 6, 1) => Some(UnitId::SheikElDin_6_1),
        (SectionName::Sherif, 0, 0) => Some(UnitId::Sherif_0_0),
        (SectionName::Sherif, 1, 0) => Some(UnitId::Sherif_1_0),
        (SectionName::Sherif, 1, 1) => Some(UnitId::Sherif_1_1),
        (SectionName::Sherif, 2, 0) => Some(UnitId::Sherif_2_0),
        (SectionName::Sherif, 2, 1) => Some(UnitId::Sherif_2_1),
        (SectionName::Taiasha, 0, 0) => Some(UnitId::Taiasha_0_0),
        (SectionName::Taiasha, 0, 1) => Some(UnitId::Taiasha_0_1),
        (SectionName::Taiasha, 1, 0) => Some(UnitId::Taiasha_1_0),
        (SectionName::Taiasha, 1, 1) => Some(UnitId::Taiasha_1_1),
        (SectionName::Taiasha, 2, 0) => Some(UnitId::Taiasha_2_0),
        (SectionName::Taiasha, 2, 1) => Some(UnitId::Taiasha_2_1),
        (SectionName::Taiasha, 3, 0) => Some(UnitId::Taiasha_3_0),
        (SectionName::Taiasha, 3, 1) => Some(UnitId::Taiasha_3_1),
        (SectionName::Taiasha, 4, 0) => Some(UnitId::Taiasha_4_0),
        (SectionName::Taiasha, 4, 1) => Some(UnitId::Taiasha_4_1),
        (SectionName::Taiasha, 5, 0) => Some(UnitId::Taiasha_5_0),
        (SectionName::Taiasha, 5, 1) => Some(UnitId::Taiasha_5_1),
        (SectionName::Taiasha, 6, 0) => Some(UnitId::Taiasha_6_0),
        (SectionName::Taiasha, 6, 1) => Some(UnitId::Taiasha_6_1),
        (SectionName::JaalinI, 0, 0) => Some(UnitId::JaalinI_0_0),
        (SectionName::JaalinI, 0, 1) => Some(UnitId::JaalinI_0_1),
        (SectionName::JaalinI, 1, 0) => Some(UnitId::JaalinI_1_0),
        (SectionName::JaalinI, 1, 1) => Some(UnitId::JaalinI_1_1),
        (SectionName::JaalinI, 2, 0) => Some(UnitId::JaalinI_2_0),
        (SectionName::JaalinI, 2, 1) => Some(UnitId::JaalinI_2_1),
        (SectionName::JaalinI, 3, 0) => Some(UnitId::JaalinI_3_0),
        (SectionName::JaalinI, 3, 1) => Some(UnitId::JaalinI_3_1),
        (SectionName::JaalinI, 4, 0) => Some(UnitId::JaalinI_4_0),
        (SectionName::JaalinI, 4, 1) => Some(UnitId::JaalinI_4_1),
        (SectionName::JaalinI, 5, 0) => Some(UnitId::JaalinI_5_0),
        (SectionName::JaalinI, 5, 1) => Some(UnitId::JaalinI_5_1),
        (SectionName::JaalinI, 6, 0) => Some(UnitId::JaalinI_6_0),
        (SectionName::JaalinI, 6, 1) => Some(UnitId::JaalinI_6_1),
        (SectionName::MulazminI, 0, 0) => Some(UnitId::MulazminI_0_0),
        (SectionName::MulazminI, 0, 1) => Some(UnitId::MulazminI_0_1),
        (SectionName::MulazminI, 1, 0) => Some(UnitId::MulazminI_1_0),
        (SectionName::MulazminI, 1, 1) => Some(UnitId::MulazminI_1_1),
        (SectionName::MulazminI, 2, 0) => Some(UnitId::MulazminI_2_0),
        (SectionName::MulazminI, 2, 1) => Some(UnitId::MulazminI_2_1),
        (SectionName::MulazminI, 3, 0) => Some(UnitId::MulazminI_3_0),
        (SectionName::MulazminI, 3, 1) => Some(UnitId::MulazminI_3_1),
        (SectionName::MulazminI, 4, 0) => Some(UnitId::MulazminI_4_0),
        (SectionName::MulazminI, 4, 1) => Some(UnitId::MulazminI_4_1),
        (SectionName::MulazminI, 5, 0) => Some(UnitId::MulazminI_5_0),
        (SectionName::MulazminI, 5, 1) => Some(UnitId::MulazminI_5_1),
        (SectionName::MulazminI, 6, 0) => Some(UnitId::MulazminI_6_0),
        (SectionName::MulazminI, 6, 1) => Some(UnitId::MulazminI_6_1),
        (SectionName::MulazminI, 7, 0) => Some(UnitId::MulazminI_7_0),
        (SectionName::MulazminI, 7, 1) => Some(UnitId::MulazminI_7_1),
        (SectionName::Yakub, 0, 0) => Some(UnitId::Yakub_0_0),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// One physical counter, one id: `section_pos` must be injective across
    /// `UnitId::ALL`. The removed `Gordon` alias (same section position as
    /// `BritishBoats_3_1`) let the bot deploy the Gordon counter twice --
    /// once per id -- because the engine's AlreadyDeployed guard is keyed by
    /// id, not by section position.
    #[test]
    fn section_pos_is_injective() {
        let mut seen = std::collections::HashSet::new();
        for &id in UnitId::ALL {
            let pos = id.section_pos();
            assert!(
                seen.insert(pos),
                "two UnitIds share section position {pos:?}: this aliasing breaks the \
                 AlreadyDeployed guard (one physical counter, two ids)"
            );
        }
    }
}
