//! Auto-generated unit ID enum. Do not edit by hand.
#![allow(non_camel_case_types)]

use omdurman_types::SectionName;
use serde::{Deserialize, Serialize};

/// Stable identifier for a counter on the map.
///
/// Each variant corresponds to a unique `(section, col, row)` position
/// on the sprite sheet, excluding non-unit sections (upper/lower green,
/// British Boats).
#[derive(Serialize, Deserialize, Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub enum UnitId {
    Gordon,
    AliWadHelu_0_0,
    AliWadHelu_0_1,
    AliWadHelu_1_0,
    AliWadHelu_1_1,
    AliWadHelu_2_0,
    AliWadHelu_2_1,
    AliWadHelu_3_0,
    AliWadHelu_3_1,
    AliWadHelu_4_0,
    AliWadHelu_4_1,
    AliWadHelu_5_0,
    AliWadHelu_5_1,
    Baggara_0_0,
    Baggara_0_1,
    Baggara_1_0,
    Baggara_1_1,
    Baggara_2_0,
    Baggara_2_1,
    Baggara_3_0,
    Baggara_3_1,
    Baggara_4_0,
    Baggara_4_1,
    Baggara_5_0,
    Baggara_5_1,
    BritishBoats_3_0,
    BritishBoats_3_1,
    BritishBoats_4_0,
    BritishBoats_4_1,
    BritishBoats_5_0,
    BritishBoats_5_1,
    BritishBoats_6_0,
    BritishBoats_6_1,
    BritishBoats_7_0,
    BritishBoats_7_1,
    BritishArmy_0_0,
    BritishArmy_0_1,
    BritishArmy_1_0,
    BritishArmy_1_1,
    BritishArmy_2_0,
    BritishArmy_2_1,
    BritishArmy_3_0,
    BritishArmy_3_1,
    BritishArmy_4_0,
    BritishArmy_4_1,
    BritishArmy_5_0,
    BritishArmy_5_1,
    BritishArmy_6_0,
    BritishArmy_6_1,
    BritishArmy_7_0,
    BritishArmy_7_1,
    Danagla_0_0,
    Degheim_0_0,
    EgyptianArmy_0_0,
    EgyptianArmy_0_1,
    EgyptianArmy_1_0,
    EgyptianArmy_1_1,
    EgyptianArmy_2_0,
    EgyptianArmy_2_1,
    EgyptianArmy_3_0,
    EgyptianArmy_3_1,
    EgyptianArmy_4_0,
    EgyptianArmy_4_1,
    EgyptianArmy_5_0,
    EgyptianArmy_5_1,
    EgyptianArmy_6_0,
    EgyptianArmy_6_1,
    EgyptianArmy_7_0,
    EgyptianArmy_7_1,
    Hadendowa_0_0,
    Hadendowa_0_1,
    Hadendowa_1_0,
    Hadendowa_1_1,
    Hadendowa_2_0,
    Hadendowa_2_1,
    Hadendowa_3_0,
    Hadendowa_3_1,
    Hadendowa_4_0,
    Hadendowa_4_1,
    Hadendowa_5_0,
    Hadendowa_5_1,
    Hadendowa_6_0,
    Hadendowa_6_1,
    Hadendowa_7_0,
    Hadendowa_7_1,
    HadendowaForts_0_0,
    HadendowaForts_0_1,
    HadendowaForts_1_0,
    HadendowaForts_1_1,
    HadendowaForts_2_0,
    HadendowaForts_2_1,
    HadendowaForts_3_0,
    HadendowaForts_3_1,
    HadendowaForts_4_0,
    HadendowaForts_4_1,
    HadendowaForts_5_0,
    HadendowaForts_5_1,
    HadendowaForts_6_0,
    HadendowaForts_6_1,
    HadendowaForts_7_0,
    HadendowaForts_7_1,
    Jehadia_0_0,
    Jehadia_0_1,
    Jehadia_1_0,
    Jehadia_1_1,
    Jehadia_2_0,
    Jehadia_2_1,
    Jehadia_3_0,
    Jehadia_3_1,
    Jehadia_4_0,
    Jehadia_4_1,
    Jehadia_5_0,
    Kehena_0_0,
    KhalifaAbdullah_0_0,
    KhalifaAbdullah_0_1,
    KhalifaAbdullah_1_0,
    KhalifaAbdullah_1_1,
    KhalifaAbdullah_2_0,
    KhalifaAbdullah_2_1,
    Kitchener_0_0,
    Kitchener_0_1,
    Kitchener_1_0,
    Kitchener_1_1,
    Kitchener_2_0,
    Kitchener_2_1,
    Kitchener_3_0,
    Kitchener_3_1,
    Kitchener_4_0,
    Kitchener_4_1,
    Kitchener_5_0,
    Kitchener_5_1,
    Kitchener_6_0,
    Kitchener_6_1,
    Kitchener_7_0,
    Kitchener_7_1,
    LowerJaalin_0_0,
    LowerJaalin_0_1,
    LowerJaalin_1_0,
    LowerJaalin_1_1,
    LowerJaalin_2_0,
    LowerJaalin_2_1,
    LowerJaalin_3_0,
    LowerJaalin_3_1,
    LowerJaalin_4_0,
    LowerJaalin_4_1,
    LowerJaalin_5_0,
    LowerJaalin_5_1,
    Mulazmin_0_0,
    OsmanDigna_0_0,
    SheikElDin_0_0,
    SheikElDin_0_1,
    SheikElDin_1_0,
    SheikElDin_1_1,
    SheikElDin_2_0,
    SheikElDin_2_1,
    SheikElDin_3_0,
    SheikElDin_3_1,
    SheikElDin_4_0,
    SheikElDin_4_1,
    SheikElDin_5_0,
    SheikElDin_5_1,
    SheikElDin_6_0,
    SheikElDin_6_1,
    Sherif_0_0,
    Sherif_1_0,
    Sherif_1_1,
    Sherif_2_0,
    Sherif_2_1,
    Taiasha_0_0,
    Taiasha_0_1,
    Taiasha_1_0,
    Taiasha_1_1,
    Taiasha_2_0,
    Taiasha_2_1,
    Taiasha_3_0,
    Taiasha_3_1,
    Taiasha_4_0,
    Taiasha_4_1,
    Taiasha_5_0,
    Taiasha_5_1,
    Taiasha_6_0,
    Taiasha_6_1,
    UpperJaalin_0_0,
    UpperJaalin_0_1,
    UpperJaalin_1_0,
    UpperJaalin_1_1,
    UpperJaalin_2_0,
    UpperJaalin_2_1,
    UpperJaalin_3_0,
    UpperJaalin_3_1,
    UpperJaalin_4_0,
    UpperJaalin_4_1,
    UpperJaalin_5_0,
    UpperJaalin_5_1,
    UpperJaalin_6_0,
    UpperJaalin_6_1,
    Yakub_0_0,
}

impl UnitId {
    /// Map back to the `(section_name, col, row)` that this ID represents.
    #[must_use]
    pub fn section_pos(self) -> (SectionName, u8, u8) {
        match self {
            UnitId::AliWadHelu_0_0 => (SectionName::AliWadHelu, 0, 0),
            UnitId::AliWadHelu_0_1 => (SectionName::AliWadHelu, 0, 1),
            UnitId::AliWadHelu_1_0 => (SectionName::AliWadHelu, 1, 0),
            UnitId::AliWadHelu_1_1 => (SectionName::AliWadHelu, 1, 1),
            UnitId::AliWadHelu_2_0 => (SectionName::AliWadHelu, 2, 0),
            UnitId::AliWadHelu_2_1 => (SectionName::AliWadHelu, 2, 1),
            UnitId::AliWadHelu_3_0 => (SectionName::AliWadHelu, 3, 0),
            UnitId::AliWadHelu_3_1 => (SectionName::AliWadHelu, 3, 1),
            UnitId::AliWadHelu_4_0 => (SectionName::AliWadHelu, 4, 0),
            UnitId::AliWadHelu_4_1 => (SectionName::AliWadHelu, 4, 1),
            UnitId::AliWadHelu_5_0 => (SectionName::AliWadHelu, 5, 0),
            UnitId::AliWadHelu_5_1 => (SectionName::AliWadHelu, 5, 1),
            UnitId::Baggara_0_0 => (SectionName::Baggara, 0, 0),
            UnitId::Baggara_0_1 => (SectionName::Baggara, 0, 1),
            UnitId::Baggara_1_0 => (SectionName::Baggara, 1, 0),
            UnitId::Baggara_1_1 => (SectionName::Baggara, 1, 1),
            UnitId::Baggara_2_0 => (SectionName::Baggara, 2, 0),
            UnitId::Baggara_2_1 => (SectionName::Baggara, 2, 1),
            UnitId::Baggara_3_0 => (SectionName::Baggara, 3, 0),
            UnitId::Baggara_3_1 => (SectionName::Baggara, 3, 1),
            UnitId::Baggara_4_0 => (SectionName::Baggara, 4, 0),
            UnitId::Baggara_4_1 => (SectionName::Baggara, 4, 1),
            UnitId::Baggara_5_0 => (SectionName::Baggara, 5, 0),
            UnitId::Baggara_5_1 => (SectionName::Baggara, 5, 1),
            UnitId::BritishBoats_3_0 => (SectionName::BritishBoats, 3, 0),
            UnitId::Gordon => (SectionName::BritishBoats, 3, 1),
            UnitId::BritishBoats_3_1 => (SectionName::BritishBoats, 3, 1),
            UnitId::BritishBoats_4_0 => (SectionName::BritishBoats, 4, 0),
            UnitId::BritishBoats_4_1 => (SectionName::BritishBoats, 4, 1),
            UnitId::BritishBoats_5_0 => (SectionName::BritishBoats, 5, 0),
            UnitId::BritishBoats_5_1 => (SectionName::BritishBoats, 5, 1),
            UnitId::BritishBoats_6_0 => (SectionName::BritishBoats, 6, 0),
            UnitId::BritishBoats_6_1 => (SectionName::BritishBoats, 6, 1),
            UnitId::BritishBoats_7_0 => (SectionName::BritishBoats, 7, 0),
            UnitId::BritishBoats_7_1 => (SectionName::BritishBoats, 7, 1),
            UnitId::BritishArmy_0_0 => (SectionName::BritishArmy, 0, 0),
            UnitId::BritishArmy_0_1 => (SectionName::BritishArmy, 0, 1),
            UnitId::BritishArmy_1_0 => (SectionName::BritishArmy, 1, 0),
            UnitId::BritishArmy_1_1 => (SectionName::BritishArmy, 1, 1),
            UnitId::BritishArmy_2_0 => (SectionName::BritishArmy, 2, 0),
            UnitId::BritishArmy_2_1 => (SectionName::BritishArmy, 2, 1),
            UnitId::BritishArmy_3_0 => (SectionName::BritishArmy, 3, 0),
            UnitId::BritishArmy_3_1 => (SectionName::BritishArmy, 3, 1),
            UnitId::BritishArmy_4_0 => (SectionName::BritishArmy, 4, 0),
            UnitId::BritishArmy_4_1 => (SectionName::BritishArmy, 4, 1),
            UnitId::BritishArmy_5_0 => (SectionName::BritishArmy, 5, 0),
            UnitId::BritishArmy_5_1 => (SectionName::BritishArmy, 5, 1),
            UnitId::BritishArmy_6_0 => (SectionName::BritishArmy, 6, 0),
            UnitId::BritishArmy_6_1 => (SectionName::BritishArmy, 6, 1),
            UnitId::BritishArmy_7_0 => (SectionName::BritishArmy, 7, 0),
            UnitId::BritishArmy_7_1 => (SectionName::BritishArmy, 7, 1),
            UnitId::Danagla_0_0 => (SectionName::Danagla, 0, 0),
            UnitId::Degheim_0_0 => (SectionName::Degheim, 0, 0),
            UnitId::EgyptianArmy_0_0 => (SectionName::EgyptianArmy, 0, 0),
            UnitId::EgyptianArmy_0_1 => (SectionName::EgyptianArmy, 0, 1),
            UnitId::EgyptianArmy_1_0 => (SectionName::EgyptianArmy, 1, 0),
            UnitId::EgyptianArmy_1_1 => (SectionName::EgyptianArmy, 1, 1),
            UnitId::EgyptianArmy_2_0 => (SectionName::EgyptianArmy, 2, 0),
            UnitId::EgyptianArmy_2_1 => (SectionName::EgyptianArmy, 2, 1),
            UnitId::EgyptianArmy_3_0 => (SectionName::EgyptianArmy, 3, 0),
            UnitId::EgyptianArmy_3_1 => (SectionName::EgyptianArmy, 3, 1),
            UnitId::EgyptianArmy_4_0 => (SectionName::EgyptianArmy, 4, 0),
            UnitId::EgyptianArmy_4_1 => (SectionName::EgyptianArmy, 4, 1),
            UnitId::EgyptianArmy_5_0 => (SectionName::EgyptianArmy, 5, 0),
            UnitId::EgyptianArmy_5_1 => (SectionName::EgyptianArmy, 5, 1),
            UnitId::EgyptianArmy_6_0 => (SectionName::EgyptianArmy, 6, 0),
            UnitId::EgyptianArmy_6_1 => (SectionName::EgyptianArmy, 6, 1),
            UnitId::EgyptianArmy_7_0 => (SectionName::EgyptianArmy, 7, 0),
            UnitId::EgyptianArmy_7_1 => (SectionName::EgyptianArmy, 7, 1),
            UnitId::Hadendowa_0_0 => (SectionName::Hadendowa, 0, 0),
            UnitId::Hadendowa_0_1 => (SectionName::Hadendowa, 0, 1),
            UnitId::Hadendowa_1_0 => (SectionName::Hadendowa, 1, 0),
            UnitId::Hadendowa_1_1 => (SectionName::Hadendowa, 1, 1),
            UnitId::Hadendowa_2_0 => (SectionName::Hadendowa, 2, 0),
            UnitId::Hadendowa_2_1 => (SectionName::Hadendowa, 2, 1),
            UnitId::Hadendowa_3_0 => (SectionName::Hadendowa, 3, 0),
            UnitId::Hadendowa_3_1 => (SectionName::Hadendowa, 3, 1),
            UnitId::Hadendowa_4_0 => (SectionName::Hadendowa, 4, 0),
            UnitId::Hadendowa_4_1 => (SectionName::Hadendowa, 4, 1),
            UnitId::Hadendowa_5_0 => (SectionName::Hadendowa, 5, 0),
            UnitId::Hadendowa_5_1 => (SectionName::Hadendowa, 5, 1),
            UnitId::Hadendowa_6_0 => (SectionName::Hadendowa, 6, 0),
            UnitId::Hadendowa_6_1 => (SectionName::Hadendowa, 6, 1),
            UnitId::Hadendowa_7_0 => (SectionName::Hadendowa, 7, 0),
            UnitId::Hadendowa_7_1 => (SectionName::Hadendowa, 7, 1),
            UnitId::HadendowaForts_0_0 => (SectionName::HadendowaForts, 0, 0),
            UnitId::HadendowaForts_0_1 => (SectionName::HadendowaForts, 0, 1),
            UnitId::HadendowaForts_1_0 => (SectionName::HadendowaForts, 1, 0),
            UnitId::HadendowaForts_1_1 => (SectionName::HadendowaForts, 1, 1),
            UnitId::HadendowaForts_2_0 => (SectionName::HadendowaForts, 2, 0),
            UnitId::HadendowaForts_2_1 => (SectionName::HadendowaForts, 2, 1),
            UnitId::HadendowaForts_3_0 => (SectionName::HadendowaForts, 3, 0),
            UnitId::HadendowaForts_3_1 => (SectionName::HadendowaForts, 3, 1),
            UnitId::HadendowaForts_4_0 => (SectionName::HadendowaForts, 4, 0),
            UnitId::HadendowaForts_4_1 => (SectionName::HadendowaForts, 4, 1),
            UnitId::HadendowaForts_5_0 => (SectionName::HadendowaForts, 5, 0),
            UnitId::HadendowaForts_5_1 => (SectionName::HadendowaForts, 5, 1),
            UnitId::HadendowaForts_6_0 => (SectionName::HadendowaForts, 6, 0),
            UnitId::HadendowaForts_6_1 => (SectionName::HadendowaForts, 6, 1),
            UnitId::HadendowaForts_7_0 => (SectionName::HadendowaForts, 7, 0),
            UnitId::HadendowaForts_7_1 => (SectionName::HadendowaForts, 7, 1),
            UnitId::Jehadia_0_0 => (SectionName::Jehadia, 0, 0),
            UnitId::Jehadia_0_1 => (SectionName::Jehadia, 0, 1),
            UnitId::Jehadia_1_0 => (SectionName::Jehadia, 1, 0),
            UnitId::Jehadia_1_1 => (SectionName::Jehadia, 1, 1),
            UnitId::Jehadia_2_0 => (SectionName::Jehadia, 2, 0),
            UnitId::Jehadia_2_1 => (SectionName::Jehadia, 2, 1),
            UnitId::Jehadia_3_0 => (SectionName::Jehadia, 3, 0),
            UnitId::Jehadia_3_1 => (SectionName::Jehadia, 3, 1),
            UnitId::Jehadia_4_0 => (SectionName::Jehadia, 4, 0),
            UnitId::Jehadia_4_1 => (SectionName::Jehadia, 4, 1),
            UnitId::Jehadia_5_0 => (SectionName::Jehadia, 5, 0),
            UnitId::Kehena_0_0 => (SectionName::Kehena, 0, 0),
            UnitId::KhalifaAbdullah_0_0 => (SectionName::KhalifaAbdullah, 0, 0),
            UnitId::KhalifaAbdullah_0_1 => (SectionName::KhalifaAbdullah, 0, 1),
            UnitId::KhalifaAbdullah_1_0 => (SectionName::KhalifaAbdullah, 1, 0),
            UnitId::KhalifaAbdullah_1_1 => (SectionName::KhalifaAbdullah, 1, 1),
            UnitId::KhalifaAbdullah_2_0 => (SectionName::KhalifaAbdullah, 2, 0),
            UnitId::KhalifaAbdullah_2_1 => (SectionName::KhalifaAbdullah, 2, 1),
            UnitId::Kitchener_0_0 => (SectionName::Kitchener, 0, 0),
            UnitId::Kitchener_0_1 => (SectionName::Kitchener, 0, 1),
            UnitId::Kitchener_1_0 => (SectionName::Kitchener, 1, 0),
            UnitId::Kitchener_1_1 => (SectionName::Kitchener, 1, 1),
            UnitId::Kitchener_2_0 => (SectionName::Kitchener, 2, 0),
            UnitId::Kitchener_2_1 => (SectionName::Kitchener, 2, 1),
            UnitId::Kitchener_3_0 => (SectionName::Kitchener, 3, 0),
            UnitId::Kitchener_3_1 => (SectionName::Kitchener, 3, 1),
            UnitId::Kitchener_4_0 => (SectionName::Kitchener, 4, 0),
            UnitId::Kitchener_4_1 => (SectionName::Kitchener, 4, 1),
            UnitId::Kitchener_5_0 => (SectionName::Kitchener, 5, 0),
            UnitId::Kitchener_5_1 => (SectionName::Kitchener, 5, 1),
            UnitId::Kitchener_6_0 => (SectionName::Kitchener, 6, 0),
            UnitId::Kitchener_6_1 => (SectionName::Kitchener, 6, 1),
            UnitId::Kitchener_7_0 => (SectionName::Kitchener, 7, 0),
            UnitId::Kitchener_7_1 => (SectionName::Kitchener, 7, 1),
            UnitId::LowerJaalin_0_0 => (SectionName::LowerJaalin, 0, 0),
            UnitId::LowerJaalin_0_1 => (SectionName::LowerJaalin, 0, 1),
            UnitId::LowerJaalin_1_0 => (SectionName::LowerJaalin, 1, 0),
            UnitId::LowerJaalin_1_1 => (SectionName::LowerJaalin, 1, 1),
            UnitId::LowerJaalin_2_0 => (SectionName::LowerJaalin, 2, 0),
            UnitId::LowerJaalin_2_1 => (SectionName::LowerJaalin, 2, 1),
            UnitId::LowerJaalin_3_0 => (SectionName::LowerJaalin, 3, 0),
            UnitId::LowerJaalin_3_1 => (SectionName::LowerJaalin, 3, 1),
            UnitId::LowerJaalin_4_0 => (SectionName::LowerJaalin, 4, 0),
            UnitId::LowerJaalin_4_1 => (SectionName::LowerJaalin, 4, 1),
            UnitId::LowerJaalin_5_0 => (SectionName::LowerJaalin, 5, 0),
            UnitId::LowerJaalin_5_1 => (SectionName::LowerJaalin, 5, 1),
            UnitId::Mulazmin_0_0 => (SectionName::Mulazmin, 0, 0),
            UnitId::OsmanDigna_0_0 => (SectionName::OsmanDigna, 0, 0),
            UnitId::SheikElDin_0_0 => (SectionName::SheikElDin, 0, 0),
            UnitId::SheikElDin_0_1 => (SectionName::SheikElDin, 0, 1),
            UnitId::SheikElDin_1_0 => (SectionName::SheikElDin, 1, 0),
            UnitId::SheikElDin_1_1 => (SectionName::SheikElDin, 1, 1),
            UnitId::SheikElDin_2_0 => (SectionName::SheikElDin, 2, 0),
            UnitId::SheikElDin_2_1 => (SectionName::SheikElDin, 2, 1),
            UnitId::SheikElDin_3_0 => (SectionName::SheikElDin, 3, 0),
            UnitId::SheikElDin_3_1 => (SectionName::SheikElDin, 3, 1),
            UnitId::SheikElDin_4_0 => (SectionName::SheikElDin, 4, 0),
            UnitId::SheikElDin_4_1 => (SectionName::SheikElDin, 4, 1),
            UnitId::SheikElDin_5_0 => (SectionName::SheikElDin, 5, 0),
            UnitId::SheikElDin_5_1 => (SectionName::SheikElDin, 5, 1),
            UnitId::SheikElDin_6_0 => (SectionName::SheikElDin, 6, 0),
            UnitId::SheikElDin_6_1 => (SectionName::SheikElDin, 6, 1),
            UnitId::Sherif_0_0 => (SectionName::Sherif, 0, 0),
            UnitId::Sherif_1_0 => (SectionName::Sherif, 1, 0),
            UnitId::Sherif_1_1 => (SectionName::Sherif, 1, 1),
            UnitId::Sherif_2_0 => (SectionName::Sherif, 2, 0),
            UnitId::Sherif_2_1 => (SectionName::Sherif, 2, 1),
            UnitId::Taiasha_0_0 => (SectionName::Taiasha, 0, 0),
            UnitId::Taiasha_0_1 => (SectionName::Taiasha, 0, 1),
            UnitId::Taiasha_1_0 => (SectionName::Taiasha, 1, 0),
            UnitId::Taiasha_1_1 => (SectionName::Taiasha, 1, 1),
            UnitId::Taiasha_2_0 => (SectionName::Taiasha, 2, 0),
            UnitId::Taiasha_2_1 => (SectionName::Taiasha, 2, 1),
            UnitId::Taiasha_3_0 => (SectionName::Taiasha, 3, 0),
            UnitId::Taiasha_3_1 => (SectionName::Taiasha, 3, 1),
            UnitId::Taiasha_4_0 => (SectionName::Taiasha, 4, 0),
            UnitId::Taiasha_4_1 => (SectionName::Taiasha, 4, 1),
            UnitId::Taiasha_5_0 => (SectionName::Taiasha, 5, 0),
            UnitId::Taiasha_5_1 => (SectionName::Taiasha, 5, 1),
            UnitId::Taiasha_6_0 => (SectionName::Taiasha, 6, 0),
            UnitId::Taiasha_6_1 => (SectionName::Taiasha, 6, 1),
            UnitId::UpperJaalin_0_0 => (SectionName::UpperJaalin, 0, 0),
            UnitId::UpperJaalin_0_1 => (SectionName::UpperJaalin, 0, 1),
            UnitId::UpperJaalin_1_0 => (SectionName::UpperJaalin, 1, 0),
            UnitId::UpperJaalin_1_1 => (SectionName::UpperJaalin, 1, 1),
            UnitId::UpperJaalin_2_0 => (SectionName::UpperJaalin, 2, 0),
            UnitId::UpperJaalin_2_1 => (SectionName::UpperJaalin, 2, 1),
            UnitId::UpperJaalin_3_0 => (SectionName::UpperJaalin, 3, 0),
            UnitId::UpperJaalin_3_1 => (SectionName::UpperJaalin, 3, 1),
            UnitId::UpperJaalin_4_0 => (SectionName::UpperJaalin, 4, 0),
            UnitId::UpperJaalin_4_1 => (SectionName::UpperJaalin, 4, 1),
            UnitId::UpperJaalin_5_0 => (SectionName::UpperJaalin, 5, 0),
            UnitId::UpperJaalin_5_1 => (SectionName::UpperJaalin, 5, 1),
            UnitId::UpperJaalin_6_0 => (SectionName::UpperJaalin, 6, 0),
            UnitId::UpperJaalin_6_1 => (SectionName::UpperJaalin, 6, 1),
            UnitId::Yakub_0_0 => (SectionName::Yakub, 0, 0),
        }
    }

    /// All valid unit IDs.
    pub const ALL: &'static [Self] = &[
        Self::Gordon,
        Self::AliWadHelu_0_0,
        Self::AliWadHelu_0_1,
        Self::AliWadHelu_1_0,
        Self::AliWadHelu_1_1,
        Self::AliWadHelu_2_0,
        Self::AliWadHelu_2_1,
        Self::AliWadHelu_3_0,
        Self::AliWadHelu_3_1,
        Self::AliWadHelu_4_0,
        Self::AliWadHelu_4_1,
        Self::AliWadHelu_5_0,
        Self::AliWadHelu_5_1,
        Self::Baggara_0_0,
        Self::Baggara_0_1,
        Self::Baggara_1_0,
        Self::Baggara_1_1,
        Self::Baggara_2_0,
        Self::Baggara_2_1,
        Self::Baggara_3_0,
        Self::Baggara_3_1,
        Self::Baggara_4_0,
        Self::Baggara_4_1,
        Self::Baggara_5_0,
        Self::Baggara_5_1,
        Self::BritishBoats_3_0,
        Self::BritishBoats_3_1,
        Self::BritishBoats_4_0,
        Self::BritishBoats_4_1,
        Self::BritishBoats_5_0,
        Self::BritishBoats_5_1,
        Self::BritishBoats_6_0,
        Self::BritishBoats_6_1,
        Self::BritishBoats_7_0,
        Self::BritishBoats_7_1,
        Self::BritishArmy_0_0,
        Self::BritishArmy_0_1,
        Self::BritishArmy_1_0,
        Self::BritishArmy_1_1,
        Self::BritishArmy_2_0,
        Self::BritishArmy_2_1,
        Self::BritishArmy_3_0,
        Self::BritishArmy_3_1,
        Self::BritishArmy_4_0,
        Self::BritishArmy_4_1,
        Self::BritishArmy_5_0,
        Self::BritishArmy_5_1,
        Self::BritishArmy_6_0,
        Self::BritishArmy_6_1,
        Self::BritishArmy_7_0,
        Self::BritishArmy_7_1,
        Self::Danagla_0_0,
        Self::Degheim_0_0,
        Self::EgyptianArmy_0_0,
        Self::EgyptianArmy_0_1,
        Self::EgyptianArmy_1_0,
        Self::EgyptianArmy_1_1,
        Self::EgyptianArmy_2_0,
        Self::EgyptianArmy_2_1,
        Self::EgyptianArmy_3_0,
        Self::EgyptianArmy_3_1,
        Self::EgyptianArmy_4_0,
        Self::EgyptianArmy_4_1,
        Self::EgyptianArmy_5_0,
        Self::EgyptianArmy_5_1,
        Self::EgyptianArmy_6_0,
        Self::EgyptianArmy_6_1,
        Self::EgyptianArmy_7_0,
        Self::EgyptianArmy_7_1,
        Self::Hadendowa_0_0,
        Self::Hadendowa_0_1,
        Self::Hadendowa_1_0,
        Self::Hadendowa_1_1,
        Self::Hadendowa_2_0,
        Self::Hadendowa_2_1,
        Self::Hadendowa_3_0,
        Self::Hadendowa_3_1,
        Self::Hadendowa_4_0,
        Self::Hadendowa_4_1,
        Self::Hadendowa_5_0,
        Self::Hadendowa_5_1,
        Self::Hadendowa_6_0,
        Self::Hadendowa_6_1,
        Self::Hadendowa_7_0,
        Self::Hadendowa_7_1,
        Self::HadendowaForts_0_0,
        Self::HadendowaForts_0_1,
        Self::HadendowaForts_1_0,
        Self::HadendowaForts_1_1,
        Self::HadendowaForts_2_0,
        Self::HadendowaForts_2_1,
        Self::HadendowaForts_3_0,
        Self::HadendowaForts_3_1,
        Self::HadendowaForts_4_0,
        Self::HadendowaForts_4_1,
        Self::HadendowaForts_5_0,
        Self::HadendowaForts_5_1,
        Self::HadendowaForts_6_0,
        Self::HadendowaForts_6_1,
        Self::HadendowaForts_7_0,
        Self::HadendowaForts_7_1,
        Self::Jehadia_0_0,
        Self::Jehadia_0_1,
        Self::Jehadia_1_0,
        Self::Jehadia_1_1,
        Self::Jehadia_2_0,
        Self::Jehadia_2_1,
        Self::Jehadia_3_0,
        Self::Jehadia_3_1,
        Self::Jehadia_4_0,
        Self::Jehadia_4_1,
        Self::Jehadia_5_0,
        Self::Kehena_0_0,
        Self::KhalifaAbdullah_0_0,
        Self::KhalifaAbdullah_0_1,
        Self::KhalifaAbdullah_1_0,
        Self::KhalifaAbdullah_1_1,
        Self::KhalifaAbdullah_2_0,
        Self::KhalifaAbdullah_2_1,
        Self::Kitchener_0_0,
        Self::Kitchener_0_1,
        Self::Kitchener_1_0,
        Self::Kitchener_1_1,
        Self::Kitchener_2_0,
        Self::Kitchener_2_1,
        Self::Kitchener_3_0,
        Self::Kitchener_3_1,
        Self::Kitchener_4_0,
        Self::Kitchener_4_1,
        Self::Kitchener_5_0,
        Self::Kitchener_5_1,
        Self::Kitchener_6_0,
        Self::Kitchener_6_1,
        Self::Kitchener_7_0,
        Self::Kitchener_7_1,
        Self::LowerJaalin_0_0,
        Self::LowerJaalin_0_1,
        Self::LowerJaalin_1_0,
        Self::LowerJaalin_1_1,
        Self::LowerJaalin_2_0,
        Self::LowerJaalin_2_1,
        Self::LowerJaalin_3_0,
        Self::LowerJaalin_3_1,
        Self::LowerJaalin_4_0,
        Self::LowerJaalin_4_1,
        Self::LowerJaalin_5_0,
        Self::LowerJaalin_5_1,
        Self::Mulazmin_0_0,
        Self::OsmanDigna_0_0,
        Self::SheikElDin_0_0,
        Self::SheikElDin_0_1,
        Self::SheikElDin_1_0,
        Self::SheikElDin_1_1,
        Self::SheikElDin_2_0,
        Self::SheikElDin_2_1,
        Self::SheikElDin_3_0,
        Self::SheikElDin_3_1,
        Self::SheikElDin_4_0,
        Self::SheikElDin_4_1,
        Self::SheikElDin_5_0,
        Self::SheikElDin_5_1,
        Self::SheikElDin_6_0,
        Self::SheikElDin_6_1,
        Self::Sherif_0_0,
        Self::Sherif_1_0,
        Self::Sherif_1_1,
        Self::Sherif_2_0,
        Self::Sherif_2_1,
        Self::Taiasha_0_0,
        Self::Taiasha_0_1,
        Self::Taiasha_1_0,
        Self::Taiasha_1_1,
        Self::Taiasha_2_0,
        Self::Taiasha_2_1,
        Self::Taiasha_3_0,
        Self::Taiasha_3_1,
        Self::Taiasha_4_0,
        Self::Taiasha_4_1,
        Self::Taiasha_5_0,
        Self::Taiasha_5_1,
        Self::Taiasha_6_0,
        Self::Taiasha_6_1,
        Self::UpperJaalin_0_0,
        Self::UpperJaalin_0_1,
        Self::UpperJaalin_1_0,
        Self::UpperJaalin_1_1,
        Self::UpperJaalin_2_0,
        Self::UpperJaalin_2_1,
        Self::UpperJaalin_3_0,
        Self::UpperJaalin_3_1,
        Self::UpperJaalin_4_0,
        Self::UpperJaalin_4_1,
        Self::UpperJaalin_5_0,
        Self::UpperJaalin_5_1,
        Self::UpperJaalin_6_0,
        Self::UpperJaalin_6_1,
        Self::Yakub_0_0,
    ];

    /// The faction of this unit, from the annotations data.
    #[must_use]
    pub fn faction(self) -> Option<omdurman_types::Faction> {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.faction)
            .flatten()
    }

    /// The [`UnitKind`](omdurman_types::UnitKind) of this unit, from the annotations data.
    #[must_use]
    pub fn kind(self) -> Option<omdurman_types::UnitKind> {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.kind)
            .flatten()
    }

    /// The [`SpriteColor`](omdurman_types::SpriteColor) of this unit's sprite.
    #[must_use]
    pub fn color(self) -> omdurman_types::SpriteColor {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.color)
            .unwrap_or(omdurman_types::SpriteColor::SandBlack)
    }

    /// The display text of this unit's sprite.
    #[must_use]
    pub fn text(self) -> &'static str {
        let (s, c, r) = self.section_pos();
        crate::sprite_data::sprite_data_for(s, c, r)
            .map(|d| d.text)
            .unwrap_or("")
    }
}

/// Look up the [`UnitId`] for a given sprite-sheet position.
#[must_use]
pub fn unit_id_for_section_pos(section: SectionName, col: u8, row: u8) -> Option<UnitId> {
    match (section, col, row) {
        (SectionName::AliWadHelu, 0, 0) => Some(UnitId::AliWadHelu_0_0),
        (SectionName::AliWadHelu, 0, 1) => Some(UnitId::AliWadHelu_0_1),
        (SectionName::AliWadHelu, 1, 0) => Some(UnitId::AliWadHelu_1_0),
        (SectionName::AliWadHelu, 1, 1) => Some(UnitId::AliWadHelu_1_1),
        (SectionName::AliWadHelu, 2, 0) => Some(UnitId::AliWadHelu_2_0),
        (SectionName::AliWadHelu, 2, 1) => Some(UnitId::AliWadHelu_2_1),
        (SectionName::AliWadHelu, 3, 0) => Some(UnitId::AliWadHelu_3_0),
        (SectionName::AliWadHelu, 3, 1) => Some(UnitId::AliWadHelu_3_1),
        (SectionName::AliWadHelu, 4, 0) => Some(UnitId::AliWadHelu_4_0),
        (SectionName::AliWadHelu, 4, 1) => Some(UnitId::AliWadHelu_4_1),
        (SectionName::AliWadHelu, 5, 0) => Some(UnitId::AliWadHelu_5_0),
        (SectionName::AliWadHelu, 5, 1) => Some(UnitId::AliWadHelu_5_1),
        (SectionName::Baggara, 0, 0) => Some(UnitId::Baggara_0_0),
        (SectionName::Baggara, 0, 1) => Some(UnitId::Baggara_0_1),
        (SectionName::Baggara, 1, 0) => Some(UnitId::Baggara_1_0),
        (SectionName::Baggara, 1, 1) => Some(UnitId::Baggara_1_1),
        (SectionName::Baggara, 2, 0) => Some(UnitId::Baggara_2_0),
        (SectionName::Baggara, 2, 1) => Some(UnitId::Baggara_2_1),
        (SectionName::Baggara, 3, 0) => Some(UnitId::Baggara_3_0),
        (SectionName::Baggara, 3, 1) => Some(UnitId::Baggara_3_1),
        (SectionName::Baggara, 4, 0) => Some(UnitId::Baggara_4_0),
        (SectionName::Baggara, 4, 1) => Some(UnitId::Baggara_4_1),
        (SectionName::Baggara, 5, 0) => Some(UnitId::Baggara_5_0),
        (SectionName::Baggara, 5, 1) => Some(UnitId::Baggara_5_1),
        (SectionName::BritishBoats, 3, 0) => Some(UnitId::BritishBoats_3_0),
        (SectionName::BritishBoats, 3, 1) => Some(UnitId::BritishBoats_3_1),
        (SectionName::BritishBoats, 4, 0) => Some(UnitId::BritishBoats_4_0),
        (SectionName::BritishBoats, 4, 1) => Some(UnitId::BritishBoats_4_1),
        (SectionName::BritishBoats, 5, 0) => Some(UnitId::BritishBoats_5_0),
        (SectionName::BritishBoats, 5, 1) => Some(UnitId::BritishBoats_5_1),
        (SectionName::BritishBoats, 6, 0) => Some(UnitId::BritishBoats_6_0),
        (SectionName::BritishBoats, 6, 1) => Some(UnitId::BritishBoats_6_1),
        (SectionName::BritishBoats, 7, 0) => Some(UnitId::BritishBoats_7_0),
        (SectionName::BritishBoats, 7, 1) => Some(UnitId::BritishBoats_7_1),
        (SectionName::BritishArmy, 0, 0) => Some(UnitId::BritishArmy_0_0),
        (SectionName::BritishArmy, 0, 1) => Some(UnitId::BritishArmy_0_1),
        (SectionName::BritishArmy, 1, 0) => Some(UnitId::BritishArmy_1_0),
        (SectionName::BritishArmy, 1, 1) => Some(UnitId::BritishArmy_1_1),
        (SectionName::BritishArmy, 2, 0) => Some(UnitId::BritishArmy_2_0),
        (SectionName::BritishArmy, 2, 1) => Some(UnitId::BritishArmy_2_1),
        (SectionName::BritishArmy, 3, 0) => Some(UnitId::BritishArmy_3_0),
        (SectionName::BritishArmy, 3, 1) => Some(UnitId::BritishArmy_3_1),
        (SectionName::BritishArmy, 4, 0) => Some(UnitId::BritishArmy_4_0),
        (SectionName::BritishArmy, 4, 1) => Some(UnitId::BritishArmy_4_1),
        (SectionName::BritishArmy, 5, 0) => Some(UnitId::BritishArmy_5_0),
        (SectionName::BritishArmy, 5, 1) => Some(UnitId::BritishArmy_5_1),
        (SectionName::BritishArmy, 6, 0) => Some(UnitId::BritishArmy_6_0),
        (SectionName::BritishArmy, 6, 1) => Some(UnitId::BritishArmy_6_1),
        (SectionName::BritishArmy, 7, 0) => Some(UnitId::BritishArmy_7_0),
        (SectionName::BritishArmy, 7, 1) => Some(UnitId::BritishArmy_7_1),
        (SectionName::Danagla, 0, 0) => Some(UnitId::Danagla_0_0),
        (SectionName::Degheim, 0, 0) => Some(UnitId::Degheim_0_0),
        (SectionName::EgyptianArmy, 0, 0) => Some(UnitId::EgyptianArmy_0_0),
        (SectionName::EgyptianArmy, 0, 1) => Some(UnitId::EgyptianArmy_0_1),
        (SectionName::EgyptianArmy, 1, 0) => Some(UnitId::EgyptianArmy_1_0),
        (SectionName::EgyptianArmy, 1, 1) => Some(UnitId::EgyptianArmy_1_1),
        (SectionName::EgyptianArmy, 2, 0) => Some(UnitId::EgyptianArmy_2_0),
        (SectionName::EgyptianArmy, 2, 1) => Some(UnitId::EgyptianArmy_2_1),
        (SectionName::EgyptianArmy, 3, 0) => Some(UnitId::EgyptianArmy_3_0),
        (SectionName::EgyptianArmy, 3, 1) => Some(UnitId::EgyptianArmy_3_1),
        (SectionName::EgyptianArmy, 4, 0) => Some(UnitId::EgyptianArmy_4_0),
        (SectionName::EgyptianArmy, 4, 1) => Some(UnitId::EgyptianArmy_4_1),
        (SectionName::EgyptianArmy, 5, 0) => Some(UnitId::EgyptianArmy_5_0),
        (SectionName::EgyptianArmy, 5, 1) => Some(UnitId::EgyptianArmy_5_1),
        (SectionName::EgyptianArmy, 6, 0) => Some(UnitId::EgyptianArmy_6_0),
        (SectionName::EgyptianArmy, 6, 1) => Some(UnitId::EgyptianArmy_6_1),
        (SectionName::EgyptianArmy, 7, 0) => Some(UnitId::EgyptianArmy_7_0),
        (SectionName::EgyptianArmy, 7, 1) => Some(UnitId::EgyptianArmy_7_1),
        (SectionName::Hadendowa, 0, 0) => Some(UnitId::Hadendowa_0_0),
        (SectionName::Hadendowa, 0, 1) => Some(UnitId::Hadendowa_0_1),
        (SectionName::Hadendowa, 1, 0) => Some(UnitId::Hadendowa_1_0),
        (SectionName::Hadendowa, 1, 1) => Some(UnitId::Hadendowa_1_1),
        (SectionName::Hadendowa, 2, 0) => Some(UnitId::Hadendowa_2_0),
        (SectionName::Hadendowa, 2, 1) => Some(UnitId::Hadendowa_2_1),
        (SectionName::Hadendowa, 3, 0) => Some(UnitId::Hadendowa_3_0),
        (SectionName::Hadendowa, 3, 1) => Some(UnitId::Hadendowa_3_1),
        (SectionName::Hadendowa, 4, 0) => Some(UnitId::Hadendowa_4_0),
        (SectionName::Hadendowa, 4, 1) => Some(UnitId::Hadendowa_4_1),
        (SectionName::Hadendowa, 5, 0) => Some(UnitId::Hadendowa_5_0),
        (SectionName::Hadendowa, 5, 1) => Some(UnitId::Hadendowa_5_1),
        (SectionName::Hadendowa, 6, 0) => Some(UnitId::Hadendowa_6_0),
        (SectionName::Hadendowa, 6, 1) => Some(UnitId::Hadendowa_6_1),
        (SectionName::Hadendowa, 7, 0) => Some(UnitId::Hadendowa_7_0),
        (SectionName::Hadendowa, 7, 1) => Some(UnitId::Hadendowa_7_1),
        (SectionName::HadendowaForts, 0, 0) => Some(UnitId::HadendowaForts_0_0),
        (SectionName::HadendowaForts, 0, 1) => Some(UnitId::HadendowaForts_0_1),
        (SectionName::HadendowaForts, 1, 0) => Some(UnitId::HadendowaForts_1_0),
        (SectionName::HadendowaForts, 1, 1) => Some(UnitId::HadendowaForts_1_1),
        (SectionName::HadendowaForts, 2, 0) => Some(UnitId::HadendowaForts_2_0),
        (SectionName::HadendowaForts, 2, 1) => Some(UnitId::HadendowaForts_2_1),
        (SectionName::HadendowaForts, 3, 0) => Some(UnitId::HadendowaForts_3_0),
        (SectionName::HadendowaForts, 3, 1) => Some(UnitId::HadendowaForts_3_1),
        (SectionName::HadendowaForts, 4, 0) => Some(UnitId::HadendowaForts_4_0),
        (SectionName::HadendowaForts, 4, 1) => Some(UnitId::HadendowaForts_4_1),
        (SectionName::HadendowaForts, 5, 0) => Some(UnitId::HadendowaForts_5_0),
        (SectionName::HadendowaForts, 5, 1) => Some(UnitId::HadendowaForts_5_1),
        (SectionName::HadendowaForts, 6, 0) => Some(UnitId::HadendowaForts_6_0),
        (SectionName::HadendowaForts, 6, 1) => Some(UnitId::HadendowaForts_6_1),
        (SectionName::HadendowaForts, 7, 0) => Some(UnitId::HadendowaForts_7_0),
        (SectionName::HadendowaForts, 7, 1) => Some(UnitId::HadendowaForts_7_1),
        (SectionName::Jehadia, 0, 0) => Some(UnitId::Jehadia_0_0),
        (SectionName::Jehadia, 0, 1) => Some(UnitId::Jehadia_0_1),
        (SectionName::Jehadia, 1, 0) => Some(UnitId::Jehadia_1_0),
        (SectionName::Jehadia, 1, 1) => Some(UnitId::Jehadia_1_1),
        (SectionName::Jehadia, 2, 0) => Some(UnitId::Jehadia_2_0),
        (SectionName::Jehadia, 2, 1) => Some(UnitId::Jehadia_2_1),
        (SectionName::Jehadia, 3, 0) => Some(UnitId::Jehadia_3_0),
        (SectionName::Jehadia, 3, 1) => Some(UnitId::Jehadia_3_1),
        (SectionName::Jehadia, 4, 0) => Some(UnitId::Jehadia_4_0),
        (SectionName::Jehadia, 4, 1) => Some(UnitId::Jehadia_4_1),
        (SectionName::Jehadia, 5, 0) => Some(UnitId::Jehadia_5_0),
        (SectionName::Kehena, 0, 0) => Some(UnitId::Kehena_0_0),
        (SectionName::KhalifaAbdullah, 0, 0) => Some(UnitId::KhalifaAbdullah_0_0),
        (SectionName::KhalifaAbdullah, 0, 1) => Some(UnitId::KhalifaAbdullah_0_1),
        (SectionName::KhalifaAbdullah, 1, 0) => Some(UnitId::KhalifaAbdullah_1_0),
        (SectionName::KhalifaAbdullah, 1, 1) => Some(UnitId::KhalifaAbdullah_1_1),
        (SectionName::KhalifaAbdullah, 2, 0) => Some(UnitId::KhalifaAbdullah_2_0),
        (SectionName::KhalifaAbdullah, 2, 1) => Some(UnitId::KhalifaAbdullah_2_1),
        (SectionName::Kitchener, 0, 0) => Some(UnitId::Kitchener_0_0),
        (SectionName::Kitchener, 0, 1) => Some(UnitId::Kitchener_0_1),
        (SectionName::Kitchener, 1, 0) => Some(UnitId::Kitchener_1_0),
        (SectionName::Kitchener, 1, 1) => Some(UnitId::Kitchener_1_1),
        (SectionName::Kitchener, 2, 0) => Some(UnitId::Kitchener_2_0),
        (SectionName::Kitchener, 2, 1) => Some(UnitId::Kitchener_2_1),
        (SectionName::Kitchener, 3, 0) => Some(UnitId::Kitchener_3_0),
        (SectionName::Kitchener, 3, 1) => Some(UnitId::Kitchener_3_1),
        (SectionName::Kitchener, 4, 0) => Some(UnitId::Kitchener_4_0),
        (SectionName::Kitchener, 4, 1) => Some(UnitId::Kitchener_4_1),
        (SectionName::Kitchener, 5, 0) => Some(UnitId::Kitchener_5_0),
        (SectionName::Kitchener, 5, 1) => Some(UnitId::Kitchener_5_1),
        (SectionName::Kitchener, 6, 0) => Some(UnitId::Kitchener_6_0),
        (SectionName::Kitchener, 6, 1) => Some(UnitId::Kitchener_6_1),
        (SectionName::Kitchener, 7, 0) => Some(UnitId::Kitchener_7_0),
        (SectionName::Kitchener, 7, 1) => Some(UnitId::Kitchener_7_1),
        (SectionName::LowerJaalin, 0, 0) => Some(UnitId::LowerJaalin_0_0),
        (SectionName::LowerJaalin, 0, 1) => Some(UnitId::LowerJaalin_0_1),
        (SectionName::LowerJaalin, 1, 0) => Some(UnitId::LowerJaalin_1_0),
        (SectionName::LowerJaalin, 1, 1) => Some(UnitId::LowerJaalin_1_1),
        (SectionName::LowerJaalin, 2, 0) => Some(UnitId::LowerJaalin_2_0),
        (SectionName::LowerJaalin, 2, 1) => Some(UnitId::LowerJaalin_2_1),
        (SectionName::LowerJaalin, 3, 0) => Some(UnitId::LowerJaalin_3_0),
        (SectionName::LowerJaalin, 3, 1) => Some(UnitId::LowerJaalin_3_1),
        (SectionName::LowerJaalin, 4, 0) => Some(UnitId::LowerJaalin_4_0),
        (SectionName::LowerJaalin, 4, 1) => Some(UnitId::LowerJaalin_4_1),
        (SectionName::LowerJaalin, 5, 0) => Some(UnitId::LowerJaalin_5_0),
        (SectionName::LowerJaalin, 5, 1) => Some(UnitId::LowerJaalin_5_1),
        (SectionName::Mulazmin, 0, 0) => Some(UnitId::Mulazmin_0_0),
        (SectionName::OsmanDigna, 0, 0) => Some(UnitId::OsmanDigna_0_0),
        (SectionName::SheikElDin, 0, 0) => Some(UnitId::SheikElDin_0_0),
        (SectionName::SheikElDin, 0, 1) => Some(UnitId::SheikElDin_0_1),
        (SectionName::SheikElDin, 1, 0) => Some(UnitId::SheikElDin_1_0),
        (SectionName::SheikElDin, 1, 1) => Some(UnitId::SheikElDin_1_1),
        (SectionName::SheikElDin, 2, 0) => Some(UnitId::SheikElDin_2_0),
        (SectionName::SheikElDin, 2, 1) => Some(UnitId::SheikElDin_2_1),
        (SectionName::SheikElDin, 3, 0) => Some(UnitId::SheikElDin_3_0),
        (SectionName::SheikElDin, 3, 1) => Some(UnitId::SheikElDin_3_1),
        (SectionName::SheikElDin, 4, 0) => Some(UnitId::SheikElDin_4_0),
        (SectionName::SheikElDin, 4, 1) => Some(UnitId::SheikElDin_4_1),
        (SectionName::SheikElDin, 5, 0) => Some(UnitId::SheikElDin_5_0),
        (SectionName::SheikElDin, 5, 1) => Some(UnitId::SheikElDin_5_1),
        (SectionName::SheikElDin, 6, 0) => Some(UnitId::SheikElDin_6_0),
        (SectionName::SheikElDin, 6, 1) => Some(UnitId::SheikElDin_6_1),
        (SectionName::Sherif, 0, 0) => Some(UnitId::Sherif_0_0),
        (SectionName::Sherif, 1, 0) => Some(UnitId::Sherif_1_0),
        (SectionName::Sherif, 1, 1) => Some(UnitId::Sherif_1_1),
        (SectionName::Sherif, 2, 0) => Some(UnitId::Sherif_2_0),
        (SectionName::Sherif, 2, 1) => Some(UnitId::Sherif_2_1),
        (SectionName::Taiasha, 0, 0) => Some(UnitId::Taiasha_0_0),
        (SectionName::Taiasha, 0, 1) => Some(UnitId::Taiasha_0_1),
        (SectionName::Taiasha, 1, 0) => Some(UnitId::Taiasha_1_0),
        (SectionName::Taiasha, 1, 1) => Some(UnitId::Taiasha_1_1),
        (SectionName::Taiasha, 2, 0) => Some(UnitId::Taiasha_2_0),
        (SectionName::Taiasha, 2, 1) => Some(UnitId::Taiasha_2_1),
        (SectionName::Taiasha, 3, 0) => Some(UnitId::Taiasha_3_0),
        (SectionName::Taiasha, 3, 1) => Some(UnitId::Taiasha_3_1),
        (SectionName::Taiasha, 4, 0) => Some(UnitId::Taiasha_4_0),
        (SectionName::Taiasha, 4, 1) => Some(UnitId::Taiasha_4_1),
        (SectionName::Taiasha, 5, 0) => Some(UnitId::Taiasha_5_0),
        (SectionName::Taiasha, 5, 1) => Some(UnitId::Taiasha_5_1),
        (SectionName::Taiasha, 6, 0) => Some(UnitId::Taiasha_6_0),
        (SectionName::Taiasha, 6, 1) => Some(UnitId::Taiasha_6_1),
        (SectionName::UpperJaalin, 0, 0) => Some(UnitId::UpperJaalin_0_0),
        (SectionName::UpperJaalin, 0, 1) => Some(UnitId::UpperJaalin_0_1),
        (SectionName::UpperJaalin, 1, 0) => Some(UnitId::UpperJaalin_1_0),
        (SectionName::UpperJaalin, 1, 1) => Some(UnitId::UpperJaalin_1_1),
        (SectionName::UpperJaalin, 2, 0) => Some(UnitId::UpperJaalin_2_0),
        (SectionName::UpperJaalin, 2, 1) => Some(UnitId::UpperJaalin_2_1),
        (SectionName::UpperJaalin, 3, 0) => Some(UnitId::UpperJaalin_3_0),
        (SectionName::UpperJaalin, 3, 1) => Some(UnitId::UpperJaalin_3_1),
        (SectionName::UpperJaalin, 4, 0) => Some(UnitId::UpperJaalin_4_0),
        (SectionName::UpperJaalin, 4, 1) => Some(UnitId::UpperJaalin_4_1),
        (SectionName::UpperJaalin, 5, 0) => Some(UnitId::UpperJaalin_5_0),
        (SectionName::UpperJaalin, 5, 1) => Some(UnitId::UpperJaalin_5_1),
        (SectionName::UpperJaalin, 6, 0) => Some(UnitId::UpperJaalin_6_0),
        (SectionName::UpperJaalin, 6, 1) => Some(UnitId::UpperJaalin_6_1),
        (SectionName::Yakub, 0, 0) => Some(UnitId::Yakub_0_0),
        _ => None,
    }
}
